/* Turkish & Arabic recipes */
addRecipe({ name: "Chicken Shawarma", cuisine: "Arabic", category: "Main Course", difficulty: "Medium", prep: "25 min", cook: "20 min", servings: 4, calories: 480, image: "https://picsum.photos/seed/chicken-shawarma/600/400", description: "Spit-style spiced chicken wrapped in warm pita with garlic sauce and pickles.", ingredients: ["Chicken","Pita Bread","Garlic","Yogurt","Cumin","Paprika","Cardamom","Lemon","Pickles","Olive Oil"], steps: ["Marinate chicken in spices and yogurt.","Roast or grill the chicken.","Slice the chicken thin.","Warm the pita bread.","Assemble with garlic sauce and pickles."], tips: ["Marinate overnight for the best flavor."], nutrition: { protein: "36 g", carbs: "38 g", fat: "18 g", fiber: "4 g" } });

addRecipe({ name: "Beef Doner Kebab", cuisine: "Turkish", category: "Main Course", difficulty: "Hard", prep: "30 min", cook: "40 min", servings: 6, calories: 560, image: "https://picsum.photos/seed/beef-doner-kebab/600/400", description: "Stacked seasoned beef roasted on a vertical spit and shaved into thin slices.", ingredients: ["Beef","Lamb Fat","Onion","Garlic","Cumin","Oregano","Paprika","Yogurt","Pita Bread","Tomato"], steps: ["Blend beef with spices and onion.","Stack the meat tightly onto a spit.","Roast slowly while turning.","Shave off the crisp outer layer.","Serve in pita with tomato and yogurt."], tips: ["Keep the meat mixture cold before stacking.","Baste the surface to keep it juicy."], nutrition: { protein: "40 g", carbs: "32 g", fat: "28 g", fiber: "3 g" } });

addRecipe({ name: "Lahmacun", cuisine: "Turkish", category: "Main Course", difficulty: "Medium", prep: "35 min", cook: "12 min", servings: 4, calories: 420, image: "https://picsum.photos/seed/lahmacun/600/400", description: "Thin crispy flatbread topped with spiced minced meat, herbs and vegetables.", ingredients: ["Flour","Ground Beef","Onion","Garlic","Tomato","Red Pepper","Parsley","Paprika","Cumin","Lemon"], steps: ["Prepare a thin dough and rest it.","Blend meat with vegetables and spices.","Spread the topping over rolled dough.","Bake in a very hot oven until crisp.","Squeeze lemon and roll to serve."], tips: ["Roll the dough as thin as possible."], nutrition: { protein: "22 g", carbs: "48 g", fat: "14 g", fiber: "4 g" } });

addRecipe({ name: "Menemen", cuisine: "Turkish", category: "Breakfast", difficulty: "Easy", prep: "10 min", cook: "15 min", servings: 2, calories: 320, image: "https://picsum.photos/seed/menemen/600/400", description: "Soft scrambled eggs cooked with tomatoes, green peppers and warm spices.", ingredients: ["Eggs","Tomato","Green Pepper","Onion","Olive Oil","Butter","Paprika","Salt","Parsley","Bread"], steps: ["Saute peppers and onion in oil.","Add chopped tomatoes and simmer.","Season with paprika and salt.","Pour in beaten eggs and stir gently.","Garnish with parsley and serve with bread."], tips: ["Cook eggs low and slow for a creamy texture."], nutrition: { protein: "16 g", carbs: "18 g", fat: "22 g", fiber: "3 g" } });

addRecipe({ name: "Cheese Borek", cuisine: "Turkish", category: "Appetizer", difficulty: "Medium", prep: "25 min", cook: "35 min", servings: 6, calories: 380, image: "https://picsum.photos/seed/cheese-borek/600/400", description: "Layered phyllo pastry filled with white cheese and herbs baked until golden.", ingredients: ["Phyllo Dough","Feta Cheese","Parsley","Eggs","Milk","Butter","Olive Oil","Yogurt","Sesame Seeds","Salt"], steps: ["Whisk eggs, milk, yogurt and oil.","Layer phyllo brushing each with the mixture.","Add cheese and parsley between layers.","Top with egg wash and sesame seeds.","Bake until golden and crisp."], tips: ["Let it rest before slicing.","Cover phyllo to stop it drying."], nutrition: { protein: "14 g", carbs: "30 g", fat: "22 g", fiber: "2 g" } });

addRecipe({ name: "Turkish Kofte", cuisine: "Turkish", category: "BBQ", difficulty: "Easy", prep: "20 min", cook: "15 min", servings: 4, calories: 440, image: "https://picsum.photos/seed/turkish-kofte/600/400", description: "Juicy grilled beef and lamb meatballs seasoned with onion, cumin and herbs.", ingredients: ["Ground Beef","Ground Lamb","Onion","Garlic","Cumin","Parsley","Breadcrumbs","Egg","Paprika","Salt"], steps: ["Combine meats with onion and spices.","Knead well and rest the mixture.","Shape into small oval patties.","Grill until charred and cooked through.","Serve with flatbread and salad."], tips: ["Chill the mixture so it holds shape."], nutrition: { protein: "30 g", carbs: "12 g", fat: "26 g", fiber: "2 g" } });

addRecipe({ name: "Iskender Kebab", cuisine: "Turkish", category: "Main Course", difficulty: "Medium", prep: "20 min", cook: "25 min", servings: 4, calories: 620, image: "https://picsum.photos/seed/iskender-kebab/600/400", description: "Sliced doner meat over pita, topped with tomato sauce, yogurt and melted butter.", ingredients: ["Beef","Pita Bread","Tomato","Butter","Yogurt","Garlic","Paprika","Olive Oil","Onion","Salt"], steps: ["Slice cooked doner meat thin.","Cut pita and layer on a plate.","Top pita with the sliced meat.","Pour hot tomato sauce over the meat.","Drizzle sizzling butter and serve with yogurt."], tips: ["Use day-old pita to soak the sauce."], nutrition: { protein: "38 g", carbs: "40 g", fat: "32 g", fiber: "3 g" } });

addRecipe({ name: "Turkish Pilav", cuisine: "Turkish", category: "Rice", difficulty: "Easy", prep: "10 min", cook: "20 min", servings: 4, calories: 300, image: "https://picsum.photos/seed/turkish-pilav/600/400", description: "Buttery rice cooked with toasted orzo pasta until fluffy and golden.", ingredients: ["Rice","Orzo Pasta","Butter","Chicken Stock","Salt","Olive Oil","Black Pepper","Water","Bay Leaf","Onion"], steps: ["Toast orzo in butter until golden.","Add rinsed rice and stir briefly.","Pour in the hot stock and season.","Cover and simmer until absorbed.","Rest, then fluff with a fork."], tips: ["Rinse the rice to remove excess starch."], nutrition: { protein: "6 g", carbs: "52 g", fat: "8 g", fiber: "2 g" } });

addRecipe({ name: "Mercimek Corbasi", cuisine: "Turkish", category: "Soup", difficulty: "Easy", prep: "15 min", cook: "30 min", servings: 4, calories: 240, image: "https://picsum.photos/seed/mercimek-corbasi/600/400", description: "Silky red lentil soup with cumin and mint, finished with lemon and paprika butter.", ingredients: ["Red Lentils","Onion","Carrot","Garlic","Cumin","Paprika","Butter","Vegetable Stock","Lemon","Mint"], steps: ["Saute onion, carrot and garlic.","Add lentils, cumin and stock.","Simmer until the lentils are soft.","Blend the soup until smooth.","Serve with lemon and paprika butter."], tips: ["Blend well for a velvety texture.","Add lemon just before serving."], nutrition: { protein: "12 g", carbs: "34 g", fat: "6 g", fiber: "9 g" } });

addRecipe({ name: "Baklava", cuisine: "Turkish", category: "Dessert", difficulty: "Hard", prep: "40 min", cook: "45 min", servings: 12, calories: 330, image: "https://picsum.photos/seed/baklava/600/400", description: "Crisp layers of buttered phyllo filled with pistachios and soaked in syrup.", ingredients: ["Phyllo Dough","Pistachios","Walnuts","Butter","Sugar","Water","Lemon","Honey","Cinnamon","Cloves"], steps: ["Brush phyllo layers with butter.","Add a nut layer in the middle.","Layer more buttered phyllo on top.","Cut into diamonds and bake until golden.","Pour cooled syrup over the hot baklava."], tips: ["Use cool syrup on hot pastry for crispness.","Let it soak for several hours."], nutrition: { protein: "5 g", carbs: "38 g", fat: "18 g", fiber: "2 g" } });

addRecipe({ name: "Kunefe", cuisine: "Turkish", category: "Dessert", difficulty: "Medium", prep: "20 min", cook: "20 min", servings: 6, calories: 420, image: "https://picsum.photos/seed/kunefe/600/400", description: "Shredded kadayif pastry layered with stretchy cheese and drenched in syrup.", ingredients: ["Kadayif Pastry","Mozzarella","Butter","Sugar","Water","Lemon","Pistachios","Cream","Salt","Rose Water"], steps: ["Toss shredded pastry with melted butter.","Press half into a pan and add cheese.","Cover with the remaining pastry.","Cook until both sides are golden.","Soak with syrup and top with pistachios."], tips: ["Serve immediately while the cheese is molten."], nutrition: { protein: "10 g", carbs: "46 g", fat: "22 g", fiber: "1 g" } });

addRecipe({ name: "Turkish Pide", cuisine: "Turkish", category: "Main Course", difficulty: "Medium", prep: "30 min", cook: "18 min", servings: 4, calories: 460, image: "https://picsum.photos/seed/turkish-pide/600/400", description: "Boat-shaped flatbread filled with spiced minced meat, cheese and egg.", ingredients: ["Flour","Yeast","Ground Beef","Onion","Tomato","Cheese","Egg","Butter","Parsley","Paprika"], steps: ["Prepare and rise the dough.","Shape dough into a boat form.","Fill with meat, tomato and cheese.","Bake until the crust is golden.","Crack an egg on top and finish baking."], tips: ["Pinch the ends tightly to hold filling."], nutrition: { protein: "24 g", carbs: "50 g", fat: "18 g", fiber: "3 g" } });

addRecipe({ name: "Falafel", cuisine: "Arabic", category: "Appetizer", difficulty: "Medium", prep: "30 min", cook: "15 min", servings: 5, calories: 350, image: "https://picsum.photos/seed/falafel/600/400", description: "Crispy fried chickpea fritters packed with garlic, herbs and warm spices.", ingredients: ["Chickpeas","Garlic","Onion","Parsley","Cilantro","Cumin","Coriander","Flour","Baking Soda","Sesame Seeds"], steps: ["Soak dried chickpeas overnight.","Blend with herbs, garlic and spices.","Rest the mixture, then shape balls.","Fry until deep golden and crisp.","Serve with tahini sauce and pita."], tips: ["Use dried, not canned, chickpeas.","Do not over-blend the mixture."], nutrition: { protein: "14 g", carbs: "36 g", fat: "14 g", fiber: "8 g" } });

addRecipe({ name: "Hummus", cuisine: "Arabic", category: "Appetizer", difficulty: "Easy", prep: "15 min", cook: "0 min", servings: 6, calories: 220, image: "https://picsum.photos/seed/hummus/600/400", description: "Creamy chickpea dip blended with tahini, lemon and garlic, drizzled with oil.", ingredients: ["Chickpeas","Tahini","Garlic","Lemon","Olive Oil","Cumin","Salt","Water","Paprika","Parsley"], steps: ["Blend chickpeas until smooth.","Add tahini, garlic and lemon.","Loosen with water and olive oil.","Season with cumin and salt.","Swirl and top with oil and paprika."], tips: ["Peel the chickpeas for extra smoothness."], nutrition: { protein: "8 g", carbs: "22 g", fat: "12 g", fiber: "6 g" } });

addRecipe({ name: "Tabbouleh", cuisine: "Arabic", category: "Salad", difficulty: "Easy", prep: "25 min", cook: "0 min", servings: 4, calories: 180, image: "https://picsum.photos/seed/tabbouleh/600/400", description: "Fresh parsley salad with bulgur, tomato, mint and a bright lemon dressing.", ingredients: ["Parsley","Bulgur","Tomato","Mint","Onion","Lemon","Olive Oil","Salt","Black Pepper","Cucumber"], steps: ["Soak bulgur until tender.","Finely chop parsley and mint.","Dice tomato, cucumber and onion.","Toss everything with the bulgur.","Dress with lemon, oil and salt."], tips: ["Drain the tomatoes to avoid sogginess."], nutrition: { protein: "5 g", carbs: "24 g", fat: "8 g", fiber: "6 g" } });

addRecipe({ name: "Maqluba", cuisine: "Arabic", category: "Rice", difficulty: "Hard", prep: "35 min", cook: "50 min", servings: 6, calories: 540, image: "https://picsum.photos/seed/maqluba/600/400", description: "Upside-down layered rice with chicken, fried eggplant and warm spices.", ingredients: ["Rice","Chicken","Eggplant","Cauliflower","Onion","Garlic","Cinnamon","Allspice","Chicken Stock","Almonds"], steps: ["Fry the eggplant and cauliflower.","Brown the chicken with spices.","Layer meat, vegetables and rice in a pot.","Add stock and cook until tender.","Flip onto a platter and top with almonds."], tips: ["Let it rest before flipping.","Flip confidently in one motion."], nutrition: { protein: "30 g", carbs: "58 g", fat: "20 g", fiber: "5 g" } });

addRecipe({ name: "Chicken Kabsa", cuisine: "Arabic", category: "Rice", difficulty: "Medium", prep: "25 min", cook: "45 min", servings: 6, calories: 520, image: "https://picsum.photos/seed/chicken-kabsa/600/400", description: "Fragrant Saudi spiced rice cooked with chicken, tomato and dried lime.", ingredients: ["Rice","Chicken","Onion","Tomato","Garlic","Dried Lime","Cardamom","Cinnamon","Cloves","Chicken Stock"], steps: ["Brown the chicken pieces.","Saute onion, garlic and spices.","Add tomato and dried lime.","Stir in rice and pour in stock.","Simmer until rice is fluffy and tender."], tips: ["Pierce the dried limes to release flavor."], nutrition: { protein: "32 g", carbs: "56 g", fat: "16 g", fiber: "4 g" } });

addRecipe({ name: "Chicken Mandi", cuisine: "Arabic", category: "Main Course", difficulty: "Hard", prep: "30 min", cook: "60 min", servings: 6, calories: 580, image: "https://picsum.photos/seed/chicken-mandi/600/400", description: "Yemeni smoky roasted chicken served over spiced basmati rice.", ingredients: ["Chicken","Basmati Rice","Onion","Garlic","Cardamom","Cloves","Turmeric","Chicken Stock","Bay Leaf","Charcoal"], steps: ["Marinate chicken in warm spices.","Roast the chicken until tender.","Cook rice in the seasoned stock.","Smoke the dish with hot charcoal.","Plate the chicken over the rice."], tips: ["Add charcoal smoke for authentic aroma.","Rest the chicken before serving."], nutrition: { protein: "34 g", carbs: "54 g", fat: "22 g", fiber: "3 g" } });

addRecipe({ name: "Fattoush", cuisine: "Arabic", category: "Salad", difficulty: "Easy", prep: "20 min", cook: "0 min", servings: 4, calories: 210, image: "https://picsum.photos/seed/fattoush/600/400", description: "Crisp mixed salad with toasted pita chips and a tangy sumac dressing.", ingredients: ["Pita Bread","Lettuce","Tomato","Cucumber","Radish","Mint","Sumac","Lemon","Olive Oil","Pomegranate Molasses"], steps: ["Toast the pita until crisp.","Chop all the fresh vegetables.","Whisk lemon, oil and sumac.","Toss the salad with the dressing.","Top with pita chips before serving."], tips: ["Add the pita last to keep it crunchy."], nutrition: { protein: "5 g", carbs: "26 g", fat: "10 g", fiber: "5 g" } });

addRecipe({ name: "Ful Medames", cuisine: "Arabic", category: "Breakfast", difficulty: "Easy", prep: "10 min", cook: "20 min", servings: 4, calories: 280, image: "https://picsum.photos/seed/ful-medames/600/400", description: "Slow-cooked fava beans mashed with garlic, lemon, cumin and olive oil.", ingredients: ["Fava Beans","Garlic","Lemon","Cumin","Olive Oil","Tomato","Parsley","Salt","Chili","Bread"], steps: ["Simmer the fava beans until soft.","Mash lightly with garlic and cumin.","Stir in lemon juice and olive oil.","Top with tomato and parsley.","Serve warm with fresh bread."], tips: ["Leave some beans whole for texture."], nutrition: { protein: "13 g", carbs: "30 g", fat: "9 g", fiber: "10 g" } });

addRecipe({ name: "Umm Ali", cuisine: "Arabic", category: "Dessert", difficulty: "Easy", prep: "15 min", cook: "25 min", servings: 6, calories: 400, image: "https://picsum.photos/seed/umm-ali/600/400", description: "Egyptian bread pudding with milk, nuts and coconut baked until golden.", ingredients: ["Puff Pastry","Milk","Cream","Sugar","Pistachios","Almonds","Coconut","Raisins","Cinnamon","Vanilla"], steps: ["Bake and crumble the puff pastry.","Warm milk with sugar and vanilla.","Layer pastry with nuts and coconut.","Pour the sweet milk over the top.","Bake with cream until bubbly and golden."], tips: ["Broil the top for a caramelized finish."], nutrition: { protein: "8 g", carbs: "44 g", fat: "20 g", fiber: "2 g" } });

addRecipe({ name: "Mujadara", cuisine: "Arabic", category: "Rice", difficulty: "Easy", prep: "15 min", cook: "35 min", servings: 4, calories: 340, image: "https://picsum.photos/seed/mujadara/600/400", description: "Comforting lentils and rice topped with sweet caramelized onions.", ingredients: ["Lentils","Rice","Onion","Olive Oil","Cumin","Garlic","Salt","Black Pepper","Water","Coriander"], steps: ["Simmer the lentils until nearly tender.","Caramelize onions in olive oil.","Add rice, cumin and water.","Cook until rice and lentils are soft.","Top with the caramelized onions."], tips: ["Cook the onions slowly for deep sweetness."], nutrition: { protein: "12 g", carbs: "52 g", fat: "8 g", fiber: "9 g" } });
