/* ==========================================================================
   ZBH Pan & Plate — Recipe Database (legacy + enriched)
   Each recipe: id, name, cuisine, category, description, ingredients[],
   prepTime, cookTime, servings, image, calories, difficulty, instructions[],
   tips[], nutrition{}. Loaded into global RECIPES via addRecipe-compatible map.
   ========================================================================== */

const RECIPES = [];

/* Helper to register a recipe with an auto id and sensible defaults. */
function addRecipe(o) {
  if (!o.id) o.id = "r" + (RECIPES.length + 1);
  o.ingredients = o.ingredients || [];
  o.steps = o.steps || [];
  o.tips = o.tips || [];
  o.nutrition = o.nutrition || { protein: "-", carbs: "-", fat: "-", fiber: "-" };
  RECIPES.push(o);
  return o;
}

const recipes = [
{id:"egg-sandwich",name:"Egg Sandwich",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"10 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&q=80",description:"A classic breakfast sandwich of softly scrambled eggs tucked between toasted bread with a spread of your choice.",ingredients:["Bread","Eggs","Butter","Salt","Black Pepper","Mayonnaise"],instructions:["Whisk the eggs with salt and pepper.","Scramble gently in butter until just set.","Toast the bread and spread with mayonnaise.","Layer the eggs between the slices and serve warm."],featured:true,calories:340,nutrition:{protein:"18 g",carbs:"30 g",fat:"16 g",fiber:"2 g"},tips:["Add a slice of cheese for extra richness."]},
{id:"bread-omelette",name:"Bread Omelette",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"5 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=600&q=80",description:"A fluffy omelette folded around buttered toast for a filling, quick meal.",ingredients:["Eggs","Bread","Butter","Onion","Salt","Black Pepper","Coriander"],instructions:["Beat the eggs with salt, pepper and chopped onion.","Pour into a buttered pan and cook until set.","Fold the omelette and place over a slice of toast.","Garnish with coriander and serve."],featured:true,calories:360,nutrition:{protein:"20 g",carbs:"26 g",fat:"18 g",fiber:"2 g"},tips:["Use a non-stick pan for easy folding."]},
{id:"french-toast",name:"French Toast",cuisine:"International",category:"Breakfast",difficulty:"Easy",prepTime:"10 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600&q=80",description:"Bread soaked in a sweet cinnamon custard and pan-fried to a golden, pillowy breakfast treat.",ingredients:["Bread","Eggs","Milk","Sugar","Cinnamon","Butter","Vanilla"],instructions:["Whisk eggs, milk, sugar, cinnamon and vanilla.","Dip bread slices into the custard.","Fry in butter until golden on both sides.","Serve with syrup or powdered sugar."],featured:true,calories:420,nutrition:{protein:"16 g",carbs:"48 g",fat:"18 g",fiber:"3 g"},tips:["Use slightly stale bread so it soaks without falling apart."]},
{id:"cheese-omelette",name:"Cheese Omelette",cuisine:"International",category:"Breakfast",difficulty:"Easy",prepTime:"5 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&q=80",description:"A soft, cheesy omelette that melts in the mouth, perfect for a protein-packed start.",ingredients:["Eggs","Cheese","Butter","Salt","Black Pepper","Milk"],instructions:["Beat eggs with milk, salt and pepper.","Pour into a buttered pan and cook until edges set.","Sprinkle cheese over half and fold.","Cook until cheese melts and serve."],featured:true,calories:390,nutrition:{protein:"24 g",carbs:"4 g",fat:"30 g",fiber:"0 g"},tips:["Lower the heat at the end so the cheese melts gently."]},
{id:"egg-fried-rice",name:"Egg Fried Rice",cuisine:"Chinese",category:"Rice",difficulty:"Easy",prepTime:"10 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",description:"Day-old rice tossed with scrambled egg, spring onion and soy for a speedy Chinese staple.",ingredients:["Rice","Eggs","Spring Onion","Soy Sauce","Garlic","Oil","Salt"],instructions:["Scramble the eggs and set aside.","Stir-fry garlic and rice on high heat.","Add soy sauce and the eggs.","Toss with spring onion and serve hot."],featured:true,calories:430,nutrition:{protein:"14 g",carbs:"68 g",fat:"12 g",fiber:"3 g"},tips:["Use cold leftover rice to keep the grains separate."]},
{id:"pancakes",name:"Pancakes",cuisine:"International",category:"Breakfast",difficulty:"Easy",prepTime:"10 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80",description:"Light, fluffy buttermilk pancakes with a golden edge, great with syrup and fruit.",ingredients:["Flour","Eggs","Milk","Sugar","Baking Powder","Butter","Salt"],instructions:["Whisk dry ingredients, then add egg and milk.","Rest the batter briefly.","Ladle onto a hot buttered pan and flip when bubbly.","Cook through and serve with toppings."],featured:true,calories:460,nutrition:{protein:"14 g",carbs:"66 g",fat:"14 g",fiber:"3 g"},tips:["Don't overmix the batter to keep pancakes fluffy."]},
{id:"butter-toast",name:"Butter Toast",cuisine:"International",category:"Breakfast",difficulty:"Easy",prepTime:"3 mins",cookTime:"5 mins",servings:2,image:"https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600&q=80",description:"Simple golden toast slathered with melting butter — the quickest comfort bite.",ingredients:["Bread","Butter","Salt"],instructions:["Toast the bread until golden.","Spread generously with butter.","Sprinkle a pinch of salt and serve."],featured:true,calories:220,nutrition:{protein:"6 g",carbs:"24 g",fat:"11 g",fiber:"2 g"},tips:["A dusting of cinnamon sugar turns it into a treat."]},
{id:"chicken-sandwich",name:"Chicken Sandwich",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568051243858-533a607809a5?w=600&q=80",description:"Grilled chicken breast with crisp lettuce and creamy mayo in soft sandwich bread.",ingredients:["Chicken","Bread","Lettuce","Mayonnaise","Tomato","Salt","Black Pepper","Oil"],instructions:["Season and grill the chicken until cooked.","Toast the bread lightly.","Spread mayo and layer chicken, lettuce and tomato.","Close the sandwich and slice."],featured:true,calories:480,nutrition:{protein:"34 g",carbs:"40 g",fat:"18 g",fiber:"3 g"},tips:["Pound the chicken flat for even cooking."]},
{id:"grilled-cheese-sandwich",name:"Grilled Cheese Sandwich",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"5 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1568051243858-533a607809a5?w=600&q=80",description:"Two slices of bread with molten cheese, griddled until crisp and golden.",ingredients:["Bread","Cheese","Butter"],instructions:["Butter the outside of the bread slices.","Place cheese between and press in a pan.","Cook on medium heat until golden on both sides.","Slice and serve while hot."],featured:true,calories:520,nutrition:{protein:"22 g",carbs:"38 g",fat:"30 g",fiber:"2 g"},tips:["Use a mix of cheeses for better flavour."]},
{id:"tuna-sandwich",name:"Tuna Sandwich",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"10 mins",cookTime:"5 mins",servings:2,image:"https://images.unsplash.com/photo-1568051243858-533a607809a5?w=600&q=80",description:"Flaked tuna mixed with mayo and crunchy veg between slices of bread.",ingredients:["Bread","Tuna","Mayonnaise","Onion","Cucumber","Lemon","Salt"],instructions:["Drain the tuna and flake it.","Mix with mayo, onion, lemon and salt.","Spread on bread with cucumber slices.","Close and serve chilled or toasted."],featured:true,calories:410,nutrition:{protein:"28 g",carbs:"34 g",fat:"16 g",fiber:"3 g"},tips:["Add sweetcorn for extra crunch and sweetness."]},
{id:"chicken-biryani",name:"Chicken Biryani",cuisine:"Pakistani",category:"Rice",difficulty:"Hard",prepTime:"30 mins",cookTime:"45 mins",servings:4,image:"https://images.unsplash.com/photo-1631292784640-2b24be784d5d?w=600&q=80",description:"Layered basmati rice and spiced chicken, steamed together with fried onions and herbs.",ingredients:["Chicken","Basmati Rice","Onion","Yogurt","Tomato","Garlic","Ginger","Garam Masala","Red Chili Powder","Turmeric","Mint","Coriander","Ghee"],instructions:["Marinate chicken in yogurt, ginger-garlic and spices.","Fry onions golden; reserve half for layering.","Cook chicken in the masala until oil separates.","Par-boil rice with whole spices.","Layer rice and chicken, top with onions and herbs, then steam (dum)."],featured:true,calories:640,nutrition:{protein:"34 g",carbs:"72 g",fat:"22 g",fiber:"4 g"},tips:["Soak rice 30 minutes for long grains; do not overcook before layering."]},
{id:"chicken-pulao",name:"Chicken Pulao",cuisine:"Pakistani",category:"Rice",difficulty:"Medium",prepTime:"20 mins",cookTime:"30 mins",servings:4,image:"https://images.unsplash.com/photo-1631292784640-2b24be784d5d?w=600&q=80",description:"One-pot rice cooked in a light, aromatic chicken stock with whole spices.",ingredients:["Chicken","Basmati Rice","Onion","Garlic","Ginger","Cumin","Black Pepper","Cloves","Cinnamon","Salt","Oil"],instructions:["Fry onions, add chicken and whole spices.","Add water to make a stock and cook the chicken.","Add soaked rice to the stock.","Cook until liquid is absorbed, then steam on low."],featured:true,calories:560,nutrition:{protein:"30 g",carbs:"66 g",fat:"16 g",fiber:"3 g"},tips:["Use 1.5 cups liquid per cup of rice for perfect grains."]},
{id:"fried-rice",name:"Fried Rice",cuisine:"Chinese",category:"Rice",difficulty:"Easy",prepTime:"15 mins",cookTime:"15 mins",servings:3,image:"https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",description:"Wok-tossed rice with egg, vegetables and soy for a quick, savoury meal.",ingredients:["Rice","Eggs","Carrot","Peas","Spring Onion","Soy Sauce","Garlic","Oil"],instructions:["Scramble eggs and set aside.","Stir-fry garlic, carrot and peas.","Add rice and soy, toss well.","Mix in egg and spring onion."],featured:true,calories:450,nutrition:{protein:"14 g",carbs:"70 g",fat:"12 g",fiber:"4 g"},tips:["Day-old rice gives the best texture."]},
{id:"chicken-chow-mein",name:"Chicken Chow Mein",cuisine:"Chinese",category:"Noodles",difficulty:"Medium",prepTime:"15 mins",cookTime:"15 mins",servings:3,image:"https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&q=80",description:"Stir-fried noodles with chicken and crunchy vegetables in a savoury sauce.",ingredients:["Noodles","Chicken","Cabbage","Carrot","Bell Pepper","Spring Onion","Soy Sauce","Garlic","Oil"],instructions:["Boil noodles and toss with a little oil.","Stir-fry chicken until cooked.","Add vegetables and stir-fry on high heat.","Add noodles and sauces, toss to combine."],featured:true,calories:480,nutrition:{protein:"28 g",carbs:"56 g",fat:"14 g",fiber:"5 g"},tips:["Keep the heat high for a smoky wok flavour."]},
{id:"hakka-noodles",name:"Hakka Noodles",cuisine:"Chinese",category:"Noodles",difficulty:"Medium",prepTime:"15 mins",cookTime:"15 mins",servings:3,image:"https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&q=80",description:"Indo-Chinese noodles loaded with vegetables and tangy sauces.",ingredients:["Noodles","Cabbage","Carrot","Bell Pepper","Spring Onion","Soy Sauce","Vinegar","Chili Sauce","Garlic"],instructions:["Boil noodles until just done and drain.","Stir-fry garlic and vegetables on high heat.","Add sauces and toss.","Add noodles and combine quickly."],featured:true,calories:420,nutrition:{protein:"12 g",carbs:"64 g",fat:"12 g",fiber:"6 g"},tips:["Keep noodles firm so they don't turn mushy."]},
{id:"chicken-wrap",name:"Chicken Wrap",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Grilled chicken and fresh veg rolled in a soft tortilla with creamy sauce.",ingredients:["Chicken","Tortilla","Lettuce","Tomato","Mayonnaise","Garlic","Salt"],instructions:["Season and grill the chicken.","Warm the tortilla.","Spread mayo and add chicken, lettuce and tomato.","Roll tightly and slice."],featured:true,calories:470,nutrition:{protein:"32 g",carbs:"40 g",fat:"18 g",fiber:"4 g"},tips:["Warm the tortilla so it rolls without cracking."]},
{id:"chicken-quesadilla",name:"Chicken Quesadilla",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"10 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"A toasted tortilla filled with chicken and melted cheese, cut into wedges.",ingredients:["Chicken","Tortilla","Cheese","Bell Pepper","Onion","Cumin","Oil"],instructions:["Cook chicken with cumin and peppers.","Layer chicken and cheese on half a tortilla.","Fold and griddle until golden and melty.","Slice into wedges."],featured:true,calories:520,nutrition:{protein:"34 g",carbs:"34 g",fat:"24 g",fiber:"3 g"},tips:["Press gently with a spatula for even browning."]},
{id:"chicken-salad-wrap",name:"Chicken Salad Wrap",cuisine:"International",category:"Salad",difficulty:"Easy",prepTime:"15 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Shredded chicken in a creamy dressing wrapped with crisp salad veg.",ingredients:["Chicken","Lettuce","Mayonnaise","Cucumber","Carrot","Tortilla","Lemon"],instructions:["Shred cooked chicken and mix with mayo and lemon.","Add grated carrot and cucumber.","Spoon onto a tortilla with lettuce.","Roll up and serve chilled."],featured:true,calories:430,nutrition:{protein:"30 g",carbs:"28 g",fat:"20 g",fiber:"4 g"},tips:["Chill the filling for a firmer wrap."]},
{id:"fried-chicken",name:"Fried Chicken",cuisine:"International",category:"BBQ",difficulty:"Medium",prepTime:"20 mins",cookTime:"30 mins",servings:4,image:"https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600&q=80",description:"Buttermilk-marinated chicken fried to a crunchy, golden, juicy finish.",ingredients:["Chicken","Flour","Buttermilk","Salt","Black Pepper","Paprika","Oil"],instructions:["Marinate chicken in buttermilk and spices.","Dredge in seasoned flour.","Deep-fry until golden and cooked through.","Drain on paper and serve."],featured:true,calories:620,nutrition:{protein:"38 g",carbs:"34 g",fat:"34 g",fiber:"2 g"},tips:["Let the coated chicken rest before frying for a crisp crust."]},
{id:"chicken-nuggets",name:"Chicken Nuggets",cuisine:"International",category:"Appetizer",difficulty:"Medium",prepTime:"15 mins",cookTime:"15 mins",servings:3,image:"https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600&q=80",description:"Bite-sized chicken pieces coated in crispy breadcrumbs and fried.",ingredients:["Chicken","Breadcrumbs","Flour","Egg","Salt","Black Pepper","Oil"],instructions:["Cut chicken into bite pieces.","Coat in flour, egg, then breadcrumbs.","Fry until golden and cooked.","Serve with a dip."],featured:true,calories:480,nutrition:{protein:"30 g",carbs:"30 g",fat:"24 g",fiber:"2 g"},tips:["Double-coat for extra crunch."]},
{id:"chicken-cutlets",name:"Chicken Cutlets",cuisine:"International",category:"Main Course",difficulty:"Medium",prepTime:"20 mins",cookTime:"20 mins",servings:4,image:"https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600&q=80",description:"Mashed-potato and chicken patties crumbed and shallow-fried.",ingredients:["Chicken","Potato","Breadcrumbs","Egg","Onion","Coriander","Salt","Oil"],instructions:["Boil and mash potatoes; mix with shredded chicken.","Shape into patties.","Coat in egg and breadcrumbs.","Fry until golden on both sides."],featured:false,calories:430,nutrition:{protein:"26 g",carbs:"36 g",fat:"18 g",fiber:"4 g"},tips:["Chill the patties before frying so they hold shape."]},
{id:"chicken-pasta",name:"Chicken Pasta",cuisine:"International",category:"Main Course",difficulty:"Medium",prepTime:"15 mins",cookTime:"20 mins",servings:3,image:"https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=600&q=80",description:"Pasta tossed with pan-seared chicken and a light garlic cream sauce.",ingredients:["Pasta","Chicken","Cream","Garlic","Olive Oil","Parmesan","Salt","Parsley"],instructions:["Boil pasta until al dente.","Sear chicken with garlic.","Add cream and parmesan to make a sauce.","Toss pasta through and garnish with parsley."],featured:false,calories:560,nutrition:{protein:"32 g",carbs:"54 g",fat:"22 g",fiber:"3 g"},tips:["Save a splash of pasta water to loosen the sauce."]},
{id:"chicken-burger",name:"Chicken Burger",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Crispy chicken fillet in a soft bun with lettuce, tomato and sauce.",ingredients:["Chicken","Bread","Lettuce","Tomato","Mayonnaise","Cheese","Oil"],instructions:["Coat and fry the chicken fillet.","Toast the bun.","Spread sauce and layer chicken, cheese, lettuce, tomato.","Close and serve."],featured:false,calories:540,nutrition:{protein:"32 g",carbs:"44 g",fat:"24 g",fiber:"3 g"},tips:["Toast the bun for better texture."]},
{id:"hamburger",name:"Hamburger",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=600&q=80",description:"Juicy beef patty in a bun with the classic lettuce-tomato-onion stack.",ingredients:["Beef","Bread","Lettuce","Tomato","Onion","Salt","Black Pepper","Ketchup"],instructions:["Season the beef and shape into patties.","Grill or fry until desired doneness.","Toast the bun.","Assemble with veg and sauce."],featured:false,calories:580,nutrition:{protein:"30 g",carbs:"42 g",fat:"30 g",fiber:"3 g"},tips:["Don't press the patty while cooking to keep juices in."]},
{id:"cheeseburger",name:"Cheeseburger",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Beef burger layered with a slice of melting cheese.",ingredients:["Beef","Bread","Cheese","Lettuce","Tomato","Onion","Salt","Ketchup"],instructions:["Season and cook the beef patty.","Add cheese on top to melt.","Toast the bun.","Build the burger with veg and sauce."],featured:false,calories:640,nutrition:{protein:"34 g",carbs:"42 g",fat:"36 g",fiber:"3 g"},tips:["Cover the pan briefly so the cheese melts fully."]},
{id:"chapli-kebab",name:"Chapli Kebab",cuisine:"Pakistani",category:"BBQ",difficulty:"Medium",prepTime:"20 mins",cookTime:"20 mins",servings:4,image:"https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80",description:"Spicy, flat Pashtun-style minced beef kebabs with herbs and tomatoes.",ingredients:["Beef","Onion","Tomato","Eggs","Coriander","Green Chili","Garam Masala","Cumin","Corn Flour","Salt"],instructions:["Mix mince with onion, tomato, herbs and spices.","Bind with egg and corn flour.","Shape into flat patties.","Shallow-fry until crisp and cooked."],featured:false,calories:460,nutrition:{protein:"30 g",carbs:"14 g",fat:"30 g",fiber:"3 g"},tips:["Keep them flat so they cook evenly."]},
{id:"beef-biryani",name:"Beef Biryani",cuisine:"Pakistani",category:"Rice",difficulty:"Hard",prepTime:"30 mins",cookTime:"50 mins",servings:4,image:"https://images.unsplash.com/photo-1631292784640-2b24be784d5d?w=600&q=80",description:"Rich biryani of tender beef layered with fragrant saffron rice.",ingredients:["Beef","Basmati Rice","Onion","Yogurt","Tomato","Garlic","Ginger","Garam Masala","Red Chili Powder","Mint","Ghee"],instructions:["Marinate beef in yogurt and spices.","Slow-cook until tender.","Par-boil rice with whole spices.","Layer with beef and herbs, then steam."],featured:false,calories:700,nutrition:{protein:"38 g",carbs:"70 g",fat:"26 g",fiber:"4 g"},tips:["A pressure cooker speeds up tenderising the beef."]},
{id:"beef-burrito",name:"Beef Burrito",cuisine:"International",category:"Main Course",difficulty:"Medium",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Seasoned beef wrapped with rice, beans and cheese in a large tortilla.",ingredients:["Beef","Tortilla","Rice","Beans","Cheese","Onion","Cumin","Salt"],instructions:["Cook spiced beef with onion and cumin.","Warm the tortilla and add rice, beans, beef, cheese.","Fold the sides and roll.","Toast lightly if desired."],featured:false,calories:620,nutrition:{protein:"34 g",carbs:"58 g",fat:"26 g",fiber:"8 g"},tips:["Don't overfill or it won't close."]},
{id:"mutton-biryani",name:"Mutton Biryani",cuisine:"Pakistani",category:"Rice",difficulty:"Hard",prepTime:"40 mins",cookTime:"60 mins",servings:4,image:"https://images.unsplash.com/photo-1631292784640-2b24be784d5d?w=600&q=80",description:"Festive biryani with succulent mutton and layered saffron rice.",ingredients:["Mutton","Basmati Rice","Onion","Yogurt","Garlic","Ginger","Garam Masala","Red Chili Powder","Mint","Coriander","Ghee"],instructions:["Marinate mutton in yogurt and spices.","Cook until tender in masala.","Par-boil rice with whole spices.","Layer and garnish, then dum for 25 minutes."],featured:false,calories:720,nutrition:{protein:"36 g",carbs:"71 g",fat:"28 g",fiber:"4 g"},tips:["Bone-in mutton gives deeper flavour."]},
{id:"fish-and-chips",name:"Fish and Chips",cuisine:"International",category:"Main Course",difficulty:"Medium",prepTime:"20 mins",cookTime:"25 mins",servings:3,image:"https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600&q=80",description:"Beer-battered fish fillets with crispy fries, a British classic.",ingredients:["Fish","Potato","Flour","Beer","Salt","Black Pepper","Oil"],instructions:["Cut potatoes into chips and fry until crisp.","Make a batter with flour, beer and salt.","Dip fish and deep-fry until golden.","Drain and serve with lemon."],featured:false,calories:680,nutrition:{protein:"30 g",carbs:"62 g",fat:"34 g",fiber:"4 g"},tips:["Keep the batter cold for a lighter crunch."]},
{id:"shrimp-fried-rice",name:"Shrimp Fried Rice",cuisine:"Chinese",category:"Rice",difficulty:"Easy",prepTime:"15 mins",cookTime:"15 mins",servings:3,image:"https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",description:"Plump shrimp stir-fried with rice, egg and vegetables in a light soy sauce.",ingredients:["Shrimp","Rice","Eggs","Peas","Spring Onion","Soy Sauce","Garlic","Oil"],instructions:["Sauté garlic and shrimp until pink.","Add rice and soy, toss well.","Fold in scrambled egg and peas.","Finish with spring onion."],featured:false,calories:460,nutrition:{protein:"22 g",carbs:"64 g",fat:"12 g",fiber:"3 g"},tips:["Pat shrimp dry so they sear instead of steam."]},
{id:"mac-and-cheese",name:"Mac and Cheese",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"10 mins",cookTime:"20 mins",servings:4,image:"https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=600&q=80",description:"Elbow pasta in a velvety cheddar cheese sauce, baked golden on top.",ingredients:["Pasta","Cheese","Milk","Butter","Flour","Salt","Black Pepper"],instructions:["Boil pasta until al dente.","Make a roux with butter and flour, add milk.","Stir in cheese to form a sauce.","Combine with pasta and bake if desired."],featured:false,calories:540,nutrition:{protein:"22 g",carbs:"56 g",fat:"24 g",fiber:"3 g"},tips:["Grate your own cheese for the smoothest sauce."]},
{id:"red-sauce-pasta",name:"Red Sauce Pasta",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"10 mins",cookTime:"20 mins",servings:3,image:"https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=600&q=80",description:"Pasta in a bright, garlicky tomato sauce with herbs.",ingredients:["Pasta","Tomato","Garlic","Olive Oil","Basil","Salt","Black Pepper"],instructions:["Boil pasta until al dente.","Sauté garlic, add tomatoes and simmer.","Season and blend or keep chunky.","Toss pasta in the sauce and add basil."],featured:false,calories:480,nutrition:{protein:"16 g",carbs:"82 g",fat:"10 g",fiber:"6 g"},tips:["A pinch of sugar balances acidic tomatoes."]},
{id:"alfredo-pasta",name:"Alfredo Pasta",cuisine:"International",category:"Main Course",difficulty:"Medium",prepTime:"10 mins",cookTime:"20 mins",servings:3,image:"https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=600&q=80",description:"Creamy parmesan and butter sauce clinging to fettuccine.",ingredients:["Pasta","Cream","Butter","Parmesan","Garlic","Salt","Black Pepper"],instructions:["Boil pasta until al dente.","Melt butter, add garlic and cream.","Stir in parmesan until smooth.","Toss pasta and season."],featured:false,calories:620,nutrition:{protein:"18 g",carbs:"60 g",fat:"34 g",fiber:"3 g"},tips:["Add pasta water to loosen the sauce if needed."]},
{id:"cheese-quesadilla",name:"Cheese Quesadilla",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"10 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Two tortillas with a gooey cheese centre, toasted crisp.",ingredients:["Cheese","Tortilla","Butter"],instructions:["Butter one side of each tortilla.","Place cheese between, buttered side out.","Griddle until golden and melty.","Cut into wedges."],featured:false,calories:460,nutrition:{protein:"20 g",carbs:"32 g",fat:"26 g",fiber:"2 g"},tips:["Use a cheese that melts well, like cheddar."]},
{id:"cheese-pizza",name:"Cheese Pizza",cuisine:"International",category:"Main Course",difficulty:"Medium",prepTime:"20 mins",cookTime:"20 mins",servings:4,image:"https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80",description:"Classic pizza with tomato base and a blanket of melted mozzarella.",ingredients:["Pizza Dough","Tomato","Cheese","Olive Oil","Oregano","Salt"],instructions:["Roll out the dough and spread tomato sauce.","Top with cheese and oregano.","Bake hot until the base is crisp.","Slice and serve."],featured:false,calories:560,nutrition:{protein:"22 g",carbs:"72 g",fat:"20 g",fiber:"4 g"},tips:["Preheat the oven as hot as it goes for a crisp base."]},
{id:"potato-wedges",name:"Potato Wedges",cuisine:"International",category:"Appetizer",difficulty:"Easy",prepTime:"10 mins",cookTime:"30 mins",servings:4,image:"https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&q=80",description:"Seasoned potato wedges baked until crisp outside and fluffy inside.",ingredients:["Potato","Olive Oil","Paprika","Salt","Black Pepper","Garlic Powder"],instructions:["Cut potatoes into wedges.","Toss with oil and spices.","Bake until golden and crisp.","Serve with dip."],featured:false,calories:280,nutrition:{protein:"5 g",carbs:"42 g",fat:"10 g",fiber:"5 g"},tips:["Soak wedges in water first for extra crispness."]},
{id:"aloo-paratha",name:"Aloo Paratha",cuisine:"Pakistani",category:"Breakfast",difficulty:"Medium",prepTime:"20 mins",cookTime:"20 mins",servings:3,image:"https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80",description:"Whole-wheat flatbread stuffed with spiced mashed potatoes.",ingredients:["Potato","Whole Wheat Flour","Onion","Coriander","Cumin","Green Chili","Ghee","Salt"],instructions:["Boil and mash potatoes with spices.","Stuff into dough balls.","Roll out gently.","Cook on a griddle with ghee until spotted."],featured:false,calories:360,nutrition:{protein:"8 g",carbs:"58 g",fat:"10 g",fiber:"6 g"},tips:["Seal the stuffing well to avoid leaks."]},
{id:"mashed-potatoes",name:"Mashed Potatoes",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"10 mins",cookTime:"20 mins",servings:4,image:"https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&q=80",description:"Buttery, creamy mashed potatoes, the ultimate comfort side.",ingredients:["Potato","Butter","Milk","Salt","Black Pepper"],instructions:["Boil potatoes until tender.","Drain and mash.","Beat in butter and warm milk.","Season and serve."],featured:false,calories:320,nutrition:{protein:"6 g",carbs:"44 g",fat:"14 g",fiber:"4 g"},tips:["Warm the milk so the mash stays smooth."]},
{id:"daal-chawal",name:"Daal Chawal",cuisine:"Pakistani",category:"Rice",difficulty:"Easy",prepTime:"15 mins",cookTime:"30 mins",servings:4,image:"https://images.unsplash.com/photo-1631292784640-2b24be784d5d?w=600&q=80",description:"Tempered lentils served with steamed rice, a everyday Pakistani staple.",ingredients:["Rice","Lentils","Onion","Garlic","Tomato","Turmeric","Cumin","Red Chili Powder","Ghee","Salt"],instructions:["Boil lentils with turmeric and salt.","Fry onion, garlic and tomato with spices.","Add to the lentils and simmer.","Serve with steamed rice."],featured:false,calories:430,nutrition:{protein:"16 g",carbs:"70 g",fat:"10 g",fiber:"10 g"},tips:["A garlic-heavy tempering lifts simple daal."]},
{id:"chana-rice",name:"Chana Rice",cuisine:"Pakistani",category:"Rice",difficulty:"Easy",prepTime:"15 mins",cookTime:"25 mins",servings:4,image:"https://images.unsplash.com/photo-1631292784640-2b24be784d5d?w=600&q=80",description:"Chickpeas cooked with rice and whole spices for a hearty one-pot meal.",ingredients:["Rice","Chickpeas","Onion","Tomato","Garlic","Cumin","Garam Masala","Salt"],instructions:["Fry onion and spices.","Add tomato and boiled chickpeas.","Stir in soaked rice and water.","Cook until the rice is done."],featured:false,calories:450,nutrition:{protein:"15 g",carbs:"78 g",fat:"8 g",fiber:"12 g"},tips:["Use canned chickpeas to save time."]},
{id:"palak-paneer",name:"Palak Paneer",cuisine:"Pakistani",category:"Curry",difficulty:"Medium",prepTime:"15 mins",cookTime:"25 mins",servings:4,image:"https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&q=80",description:"Soft paneer in a creamy, spiced spinach gravy.",ingredients:["Spinach","Paneer","Onion","Tomato","Garlic","Ginger","Cream","Garam Masala","Salt"],instructions:["Blanch and puree spinach.","Sauté onion, ginger-garlic and tomato.","Add spinach and spices.","Fold in paneer and cream, simmer."],featured:false,calories:380,nutrition:{protein:"18 g",carbs:"16 g",fat:"26 g",fiber:"6 g"},tips:["Blanch spinach quickly to keep it bright green."]},
{id:"chana-masala",name:"Chana Masala",cuisine:"Pakistani",category:"Curry",difficulty:"Medium",prepTime:"15 mins",cookTime:"25 mins",servings:4,image:"https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&q=80",description:"Chickpeas in a tangy onion-tomato masala with warm spices.",ingredients:["Chickpeas","Onion","Tomato","Garlic","Ginger","Garam Masala","Red Chili Powder","Cumin","Salt"],instructions:["Sauté onion, ginger-garlic and tomato.","Add spices and cook to a thick masala.","Add chickpeas and simmer.","Mash a few to thicken the gravy."],featured:false,calories:360,nutrition:{protein:"14 g",carbs:"52 g",fat:"10 g",fiber:"12 g"},tips:["A pinch of dried mango powder adds tang."]},
{id:"mushroom-soup",name:"Mushroom Soup",cuisine:"International",category:"Soup",difficulty:"Easy",prepTime:"10 mins",cookTime:"20 mins",servings:3,image:"https://images.unsplash.com/photo-1604503468506-a8da13d4f9b7?w=600&q=80",description:"Creamy blended mushroom soup with a hint of thyme.",ingredients:["Mushroom","Cream","Onion","Garlic","Butter","Flour","Salt","Black Pepper"],instructions:["Sauté onion, garlic and mushrooms.","Add flour and stock, simmer.","Blend until smooth, stir in cream.","Season and serve."],featured:false,calories:280,nutrition:{protein:"8 g",carbs:"18 g",fat:"20 g",fiber:"3 g"},tips:["Reserve a few mushrooms to sauté as a garnish."]},
{id:"chicken-corn-soup",name:"Chicken Corn Soup",cuisine:"International",category:"Soup",difficulty:"Easy",prepTime:"10 mins",cookTime:"20 mins",servings:3,image:"https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",description:"Comforting soup of sweetcorn and shredded chicken, lightly thickened.",ingredients:["Corn","Chicken","Egg","Corn Flour","Garlic","Salt","Black Pepper"],instructions:["Simmer chicken and corn in stock.","Shred the chicken back in.","Thicken with corn flour slurry.","Swirl in beaten egg to form ribbons."],featured:false,calories:240,nutrition:{protein:"20 g",carbs:"22 g",fat:"8 g",fiber:"3 g"},tips:["Add egg off the heat for silky threads."]},
{id:"banana-milkshake",name:"Banana Milkshake",cuisine:"International",category:"Dessert",difficulty:"Easy",prepTime:"5 mins",cookTime:"0 mins",servings:2,image:"https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&q=80",description:"Thick, creamy banana shake blended with milk and ice.",ingredients:["Banana","Milk","Sugar","Ice"],instructions:["Peel and slice the banana.","Blend with milk, sugar and ice.","Pour and serve chilled."],featured:false,calories:260,nutrition:{protein:"8 g",carbs:"44 g",fat:"6 g",fiber:"3 g"},tips:["Freeze the banana for a thicker shake."]},
{id:"strawberry-milkshake",name:"Strawberry Milkshake",cuisine:"International",category:"Dessert",difficulty:"Easy",prepTime:"5 mins",cookTime:"0 mins",servings:2,image:"https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=600&q=80",description:"Sweet pink strawberry shake with a fruity finish.",ingredients:["Strawberry","Milk","Sugar","Ice Cream"],instructions:["Hull the strawberries.","Blend with milk, sugar and ice cream.","Pour and serve."],featured:false,calories:300,nutrition:{protein:"8 g",carbs:"46 g",fat:"9 g",fiber:"2 g"},tips:["Use ripe berries for best flavour."]},
{id:"mango-shake",name:"Mango Shake",cuisine:"International",category:"Dessert",difficulty:"Easy",prepTime:"5 mins",cookTime:"0 mins",servings:2,image:"https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&q=80",description:"Rich, tropical mango milkshake, a summer favourite.",ingredients:["Mango","Milk","Sugar","Ice"],instructions:["Peel and chop the mango.","Blend with milk, sugar and ice.","Serve chilled."],featured:false,calories:280,nutrition:{protein:"7 g",carbs:"50 g",fat:"6 g",fiber:"3 g"},tips:["Use Alphonso mangoes when in season."]},
{id:"peanut-butter-sandwich",name:"Peanut Butter Sandwich",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"5 mins",cookTime:"0 mins",servings:2,image:"https://images.unsplash.com/photo-1568051243858-533a607809a5?w=600&q=80",description:"Bread spread with creamy peanut butter — a 2-minute protein snack.",ingredients:["Bread","Peanut Butter"],instructions:["Spread peanut butter on bread.","Close and slice."],featured:false,calories:320,nutrition:{protein:"13 g",carbs:"30 g",fat:"18 g",fiber:"4 g"},tips:["Add banana slices for a sweeter version."]},
{id:"oatmeal",name:"Oatmeal",cuisine:"International",category:"Breakfast",difficulty:"Easy",prepTime:"5 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&q=80",description:"Warm, filling oats cooked with milk and topped as you like.",ingredients:["Oats","Milk","Sugar","Banana","Cinnamon"],instructions:["Simmer oats in milk until thick.","Sweeten with sugar and cinnamon.","Top with sliced banana."],featured:false,calories:300,nutrition:{protein:"11 g",carbs:"50 g",fat:"7 g",fiber:"6 g"},tips:["Add a spoon of peanut butter for extra protein."]},
{id:"bean-burrito",name:"Bean Burrito",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"10 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Refried beans and rice rolled in a tortilla with cheese and salsa.",ingredients:["Tortilla","Beans","Rice","Cheese","Onion","Cumin","Salt"],instructions:["Warm beans with cumin and onion.","Lay rice, beans and cheese on a tortilla.","Roll up tightly.","Toast lightly if desired."],featured:false,calories:480,nutrition:{protein:"20 g",carbs:"72 g",fat:"12 g",fiber:"12 g"},tips:["Add avocado for creaminess."]},
{id:"chicken-wrap-2",name:"Chicken Wrap",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Grilled chicken and fresh veg in a soft tortilla with creamy sauce.",ingredients:["Chicken","Tortilla","Lettuce","Tomato","Mayonnaise","Garlic","Salt"],instructions:["Season and grill the chicken.","Warm the tortilla.","Add chicken, lettuce, tomato and mayo.","Roll tightly and slice."],featured:false,calories:470,nutrition:{protein:"32 g",carbs:"40 g",fat:"18 g",fiber:"4 g"},tips:["Add a squeeze of lemon for brightness."]},
{id:"chicken-salad-wrap-2",name:"Chicken Salad Wrap",cuisine:"International",category:"Salad",difficulty:"Easy",prepTime:"15 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Shredded chicken salad wrapped with crisp vegetables.",ingredients:["Chicken","Lettuce","Mayonnaise","Cucumber","Carrot","Tortilla","Lemon"],instructions:["Mix shredded chicken with mayo and lemon.","Add grated carrot and cucumber.","Spoon onto a tortilla with lettuce.","Roll and serve chilled."],featured:false,calories:430,nutrition:{protein:"30 g",carbs:"28 g",fat:"20 g",fiber:"4 g"},tips:["Use rotisserie chicken to save time."]},
{id:"veg-wrap",name:"Veg Wrap",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"10 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"A crunchy vegetable wrap with hummus or dressing.",ingredients:["Tortilla","Lettuce","Cucumber","Carrot","Bell Pepper","Tomato","Mayonnaise"],instructions:["Slice the vegetables thinly.","Spread sauce on the tortilla.","Layer the veg and roll up.","Slice and serve."],featured:false,calories:320,nutrition:{protein:"8 g",carbs:"42 g",fat:"12 g",fiber:"6 g"},tips:["Add hummus for extra flavour and protein."]},
{id:"club-sandwich",name:"Club Sandwich",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"15 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1568051243858-533a607809a5?w=600&q=80",description:"Triple-decker sandwich of chicken, bacon, egg and fresh veg.",ingredients:["Bread","Chicken","Cheese","Lettuce","Tomato","Egg","Mayonnaise"],instructions:["Toast the bread slices.","Layer chicken, egg, cheese, lettuce and tomato.","Spread mayo between layers.","Secure with toothpicks and slice."],featured:false,calories:560,nutrition:{protein:"34 g",carbs:"44 g",fat:"26 g",fiber:"3 g"},tips:["Toast the middle slice too for structure."]},
{id:"chicken-sandwich-2",name:"Chicken Sandwich",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568051243858-533a607809a5?w=600&q=80",description:"Grilled chicken with lettuce and mayo in soft bread.",ingredients:["Chicken","Bread","Lettuce","Mayonnaise","Tomato","Salt","Oil"],instructions:["Season and grill the chicken.","Toast the bread.","Spread mayo and layer chicken, lettuce, tomato.","Close and slice."],featured:false,calories:480,nutrition:{protein:"34 g",carbs:"40 g",fat:"18 g",fiber:"3 g"},tips:["Marinate the chicken briefly for juicier meat."]},
{id:"grilled-sandwich",name:"Grilled Sandwich",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"10 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1568051243858-533a607809a5?w=600&q=80",description:"Toasted sandwich of cheese, tomato and herbs, pressed crisp.",ingredients:["Bread","Cheese","Tomato","Butter","Oregano"],instructions:["Butter the bread outside.","Layer cheese and tomato inside.","Press on a griddle until golden.","Slice and serve."],featured:false,calories:440,nutrition:{protein:"18 g",carbs:"38 g",fat:"24 g",fiber:"3 g"},tips:["Add a slice of ham for a non-veg twist."]},
{id:"egg-sandwich-2",name:"Egg Sandwich",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"10 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&q=80",description:"Soft scrambled eggs between toasted bread, a quick bite.",ingredients:["Egg","Bread","Butter","Salt","Black Pepper","Mayonnaise"],instructions:["Scramble eggs with salt and pepper.","Toast the bread.","Spread mayo and add eggs.","Close and serve."],featured:false,calories:340,nutrition:{protein:"18 g",carbs:"30 g",fat:"16 g",fiber:"2 g"},tips:["Add spinach for a green boost."]},
{id:"bread-omelette-2",name:"Bread Omelette",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"5 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=600&q=80",description:"Fluffy omelette folded over toast with herbs.",ingredients:["Eggs","Bread","Butter","Onion","Salt","Black Pepper","Coriander"],instructions:["Beat eggs with onion, salt and pepper.","Cook in butter until set.","Fold over toast.","Garnish with coriander."],featured:false,calories:360,nutrition:{protein:"20 g",carbs:"26 g",fat:"18 g",fiber:"2 g"},tips:["Sprinkle cheese for a richer version."]},
{id:"panini",name:"Panini",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"10 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1568051243858-533a607809a5?w=600&q=80",description:"Pressed Italian-style sandwich of chicken, cheese and veg.",ingredients:["Bread","Cheese","Chicken","Tomato","Basil","Butter"],instructions:["Butter the outside of the bread.","Layer chicken, cheese, tomato and basil.","Press in a panini grill until crisp.","Slice and serve."],featured:false,calories:520,nutrition:{protein:"32 g",carbs:"44 g",fat:"22 g",fiber:"3 g"},tips:["Use ciabatta or a crusty roll."]},
{id:"meatball-sub",name:"Meatball Sub",cuisine:"International",category:"Main Course",difficulty:"Medium",prepTime:"15 mins",cookTime:"20 mins",servings:2,image:"https://images.unsplash.com/photo-1568051243858-533a607809a5?w=600&q=80",description:"Tender meatballs in tomato sauce inside a baguette with melted cheese.",ingredients:["Bread","Minced Meat","Tomato","Garlic","Cheese","Oregano","Salt"],instructions:["Form and cook meatballs in tomato sauce.","Halve the bread and fill with meatballs.","Top with cheese and melt.","Serve hot."],featured:false,calories:600,nutrition:{protein:"34 g",carbs:"54 g",fat:"26 g",fiber:"4 g"},tips:["Toast the sub before filling to avoid sogginess."]},
{id:"gyro",name:"Gyro",cuisine:"International",category:"Main Course",difficulty:"Medium",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568051243858-533a607809a5?w=600&q=80",description:"Spit-style meat with tzatziki and salad in warm pita.",ingredients:["Bread","Chicken","Yogurt","Cucumber","Garlic","Tomato","Onion","Salt"],instructions:["Cook the sliced meat with spices.","Make tzatziki with yogurt, cucumber and garlic.","Warm the pita and fill with meat and salad.","Top with tzatziki."],featured:false,calories:540,nutrition:{protein:"32 g",carbs:"46 g",fat:"22 g",fiber:"4 g"},tips:["Grate and salt the cucumber to keep tzatziki thick."]},
{id:"burrito",name:"Burrito",cuisine:"International",category:"Main Course",difficulty:"Medium",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"A big flour tortilla packed with beans, rice, meat and salsa.",ingredients:["Tortilla","Beans","Rice","Chicken","Cheese","Salsa","Cumin"],instructions:["Cook spiced chicken and warm beans.","Lay rice, beans, chicken and cheese on the tortilla.","Add salsa.","Fold and roll tightly."],featured:false,calories:640,nutrition:{protein:"36 g",carbs:"66 g",fat:"24 g",fiber:"9 g"},tips:["Warm the tortilla so it stretches when rolling."]},
{id:"chicken-burrito",name:"Chicken Burrito",cuisine:"International",category:"Main Course",difficulty:"Medium",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Seasoned chicken burrito with rice, beans and cheese.",ingredients:["Chicken","Tortilla","Rice","Beans","Cheese","Cumin","Salt"],instructions:["Cook chicken with cumin.","Warm rice and beans.","Fill tortilla with everything, top with cheese.","Roll and serve."],featured:false,calories:620,nutrition:{protein:"36 g",carbs:"60 g",fat:"24 g",fiber:"8 g"},tips:["Add corn and peppers for extra texture."]},
{id:"chicken-quesadilla-2",name:"Chicken Quesadilla",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"10 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Toasted tortilla with chicken and melted cheese, cut into wedges.",ingredients:["Chicken","Tortilla","Cheese","Bell Pepper","Onion","Cumin","Oil"],instructions:["Cook chicken with peppers and cumin.","Layer on a tortilla with cheese.","Fold and griddle until melty.","Slice into wedges."],featured:false,calories:520,nutrition:{protein:"34 g",carbs:"34 g",fat:"24 g",fiber:"3 g"},tips:["Serve with salsa and sour cream."]},
{id:"cheese-quesadilla-2",name:"Cheese Quesadilla",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"10 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Simple cheese-filled tortilla, toasted until golden.",ingredients:["Cheese","Tortilla","Butter"],instructions:["Butter the outside of the tortilla.","Add cheese inside.","Griddle until golden and melty.","Cut and serve."],featured:false,calories:460,nutrition:{protein:"20 g",carbs:"32 g",fat:"26 g",fiber:"2 g"},tips:["Add jalapeños for a kick."]},
{id:"crispy-chicken-burger",name:"Crispy Chicken Burger",cuisine:"International",category:"Main Course",difficulty:"Medium",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Crunchy fried chicken fillet burger with slaw and sauce.",ingredients:["Chicken","Bread","Cabbage","Mayonnaise","Cheese","Flour","Egg","Breadcrumbs","Oil"],instructions:["Coat chicken in flour, egg and breadcrumbs.","Fry until crisp and cooked.","Toast the bun and add slaw.","Assemble with chicken and sauce."],featured:false,calories:620,nutrition:{protein:"32 g",carbs:"48 g",fat:"30 g",fiber:"3 g"},tips:["Rest the coated fillet before frying for a better crust."]},
{id:"chicken-burger-2",name:"Chicken Burger",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Grilled chicken fillet in a soft bun with fresh veg.",ingredients:["Chicken","Bread","Lettuce","Tomato","Mayonnaise","Cheese","Oil"],instructions:["Grill the seasoned chicken.","Toast the bun.","Layer chicken, cheese, lettuce and tomato with mayo.","Close and serve."],featured:false,calories:540,nutrition:{protein:"32 g",carbs:"44 g",fat:"24 g",fiber:"3 g"},tips:["Pound the fillet flat for even cooking."]},
{id:"cheeseburger-2",name:"Cheeseburger",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Beef patty topped with melting cheese in a soft bun.",ingredients:["Beef","Bread","Cheese","Lettuce","Tomato","Onion","Salt","Ketchup"],instructions:["Season and cook the beef patty.","Add cheese to melt.","Toast the bun.","Build with veg and sauce."],featured:false,calories:640,nutrition:{protein:"34 g",carbs:"42 g",fat:"36 g",fiber:"3 g"},tips:["Toast the bun cut-side down for crunch."]},
{id:"hamburger-2",name:"Hamburger",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=600&q=80",description:"Classic beef burger with the standard veg stack.",ingredients:["Beef","Bread","Lettuce","Tomato","Onion","Salt","Black Pepper","Ketchup"],instructions:["Season and shape the beef.","Cook to taste.","Toast the bun.","Assemble with veg and ketchup."],featured:false,calories:580,nutrition:{protein:"30 g",carbs:"42 g",fat:"30 g",fiber:"3 g"},tips:["Let the patty rest a minute before serving."]},
{id:"smash-burger",name:"Smash Burger",cuisine:"International",category:"Main Course",difficulty:"Medium",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Thin, crispy-edged beef patties smashed on the griddle, doubled up with cheese.",ingredients:["Beef","Bread","Cheese","Onion","Salt","Ketchup","Mustard"],instructions:["Roll beef into balls.","Smash flat on a hot griddle.","Flip, add cheese, stack two patties.","Build in the bun with onion and sauce."],featured:false,calories:680,nutrition:{protein:"36 g",carbs:"42 g",fat:"40 g",fiber:"3 g"},tips:["High heat gives the signature lacy edges."]},
{id:"chili-dog",name:"Chili Dog",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"10 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1612392062126-2d0a761d6877?w=600&q=80",description:"Sausage in a bun topped with beef chili and cheese.",ingredients:["Bread","Sausage","Minced Meat","Tomato","Kidney Beans","Cumin","Cheese"],instructions:["Cook sausage and set aside.","Make a quick chili with meat, tomato and beans.","Place sausage in the bun.","Top with chili and cheese."],featured:false,calories:560,nutrition:{protein:"28 g",carbs:"42 g",fat:"30 g",fiber:"6 g"},tips:["Use a beefy chili for the best topping."]},
{id:"corn-dog",name:"Corn Dog",cuisine:"International",category:"Appetizer",difficulty:"Easy",prepTime:"10 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1612392062126-2d0a761d6877?w=600&q=80",description:"Sausage on a stick dipped in cornmeal batter and fried golden.",ingredients:["Sausage","Flour","Corn Flour","Milk","Egg","Sugar","Salt","Oil"],instructions:["Mix a cornmeal batter.","Skewer the sausages.","Dip in batter and deep-fry.","Drain and serve with mustard."],featured:false,calories:420,nutrition:{protein:"14 g",carbs:"36 g",fat:"24 g",fiber:"2 g"},tips:["Let excess batter drip off before frying."]},
{id:"chicken-nuggets-2",name:"Chicken Nuggets",cuisine:"International",category:"Appetizer",difficulty:"Medium",prepTime:"15 mins",cookTime:"15 mins",servings:3,image:"https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600&q=80",description:"Bite-sized crispy chicken nuggets, perfect for dipping.",ingredients:["Chicken","Breadcrumbs","Flour","Egg","Salt","Black Pepper","Oil"],instructions:["Cut chicken into bites.","Coat in flour, egg and breadcrumbs.","Fry until golden.","Serve with a dip."],featured:false,calories:480,nutrition:{protein:"30 g",carbs:"30 g",fat:"24 g",fiber:"2 g"},tips:["Bake instead of frying for a lighter option."]},
{id:"popcorn-chicken",name:"Popcorn Chicken",cuisine:"International",category:"Appetizer",difficulty:"Medium",prepTime:"15 mins",cookTime:"15 mins",servings:3,image:"https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600&q=80",description:"Small, crunchy chicken bites seasoned with spices.",ingredients:["Chicken","Flour","Corn Flour","Garlic Powder","Paprika","Salt","Oil"],instructions:["Cut chicken into small pieces.","Coat in seasoned flour.","Fry until crisp and golden.","Drain and serve."],featured:false,calories:460,nutrition:{protein:"28 g",carbs:"28 g",fat:"24 g",fiber:"2 g"},tips:["Double-fry for extra crunch."]},
{id:"chicken-tenders",name:"Chicken Tenders",cuisine:"International",category:"Appetizer",difficulty:"Medium",prepTime:"15 mins",cookTime:"15 mins",servings:3,image:"https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600&q=80",description:"Strips of chicken in a crunchy coating, great with dips.",ingredients:["Chicken","Breadcrumbs","Flour","Egg","Salt","Black Pepper","Oil"],instructions:["Cut chicken into strips.","Coat in flour, egg and breadcrumbs.","Fry until golden and cooked.","Serve with your favourite dip."],featured:false,calories:490,nutrition:{protein:"30 g",carbs:"30 g",fat:"24 g",fiber:"2 g"},tips:["Marinate in buttermilk first for tenderness."]},
{id:"fried-chicken-2",name:"Fried Chicken",cuisine:"International",category:"BBQ",difficulty:"Medium",prepTime:"20 mins",cookTime:"30 mins",servings:4,image:"https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600&q=80",description:"Buttermilk-marinated chicken fried crisp and golden.",ingredients:["Chicken","Flour","Buttermilk","Salt","Black Pepper","Paprika","Oil"],instructions:["Marinate chicken in buttermilk and spices.","Dredge in seasoned flour.","Deep-fry until golden.","Drain and serve."],featured:false,calories:620,nutrition:{protein:"38 g",carbs:"34 g",fat:"34 g",fiber:"2 g"},tips:["Let the coated chicken rest before frying."]},
{id:"roast-chicken",name:"Roast Chicken",cuisine:"International",category:"BBQ",difficulty:"Medium",prepTime:"20 mins",cookTime:"60 mins",servings:4,image:"https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600&q=80",description:"Whole chicken roasted with herbs until juicy with crisp skin.",ingredients:["Chicken","Butter","Garlic","Lemon","Rosemary","Salt","Black Pepper"],instructions:["Rub chicken with butter, garlic and herbs.","Stuff with lemon.","Roast until juices run clear.","Rest before carving."],featured:false,calories:540,nutrition:{protein:"44 g",carbs:"4 g",fat:"38 g",fiber:"1 g"},tips:["Baste occasionally for crisper skin."]},
{id:"fish-and-chips-2",name:"Fish and Chips",cuisine:"International",category:"Main Course",difficulty:"Medium",prepTime:"20 mins",cookTime:"25 mins",servings:3,image:"https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600&q=80",description:"Beer-battered fish with crisp fries and lemon.",ingredients:["Fish","Potato","Flour","Beer","Salt","Black Pepper","Oil"],instructions:["Fry chips until crisp.","Make beer batter with flour and salt.","Dip fish and deep-fry golden.","Drain and serve with lemon."],featured:false,calories:680,nutrition:{protein:"30 g",carbs:"62 g",fat:"34 g",fiber:"4 g"},tips:["Serve with tartar sauce."]},
{id:"pepperoni-pizza",name:"Pepperoni Pizza",cuisine:"International",category:"Main Course",difficulty:"Medium",prepTime:"20 mins",cookTime:"20 mins",servings:4,image:"https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80",description:"Tomato-base pizza loaded with pepperoni and mozzarella.",ingredients:["Pizza Dough","Tomato","Cheese","Pepperoni","Oregano","Olive Oil"],instructions:["Roll out dough and spread sauce.","Add cheese and pepperoni.","Bake hot until crisp.","Slice and serve."],featured:false,calories:620,nutrition:{protein:"26 g",carbs:"70 g",fat:"26 g",fiber:"4 g"},tips:["Don't overload toppings or the base stays soft."]},
{id:"margherita-pizza",name:"Margherita Pizza",cuisine:"International",category:"Main Course",difficulty:"Medium",prepTime:"20 mins",cookTime:"20 mins",servings:4,image:"https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=600&q=80",description:"Classic pizza of tomato, mozzarella and fresh basil.",ingredients:["Pizza Dough","Tomato","Cheese","Basil","Olive Oil","Salt"],instructions:["Spread tomato sauce on the dough.","Top with mozzarella and basil.","Bake until bubbling.","Finish with olive oil."],featured:false,calories:560,nutrition:{protein:"22 g",carbs:"72 g",fat:"20 g",fiber:"4 g"},tips:["Add basil after baking to keep it fresh."]},
{id:"veg-pizza",name:"Veg Pizza",cuisine:"International",category:"Main Course",difficulty:"Medium",prepTime:"20 mins",cookTime:"20 mins",servings:4,image:"https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=600&q=80",description:"Garden vegetable pizza with a cheesy base.",ingredients:["Pizza Dough","Tomato","Cheese","Bell Pepper","Onion","Mushroom","Olive Oil"],instructions:["Spread sauce on the dough.","Add cheese and sliced vegetables.","Bake until crisp.","Slice and serve."],featured:false,calories:540,nutrition:{protein:"20 g",carbs:"74 g",fat:"18 g",fiber:"5 g"},tips:["Pre-cook watery veg like mushrooms."]},
{id:"garlic-bread",name:"Garlic Bread",cuisine:"International",category:"Appetizer",difficulty:"Easy",prepTime:"10 mins",cookTime:"15 mins",servings:4,image:"https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=600&q=80",description:"Baguette slathered with garlic butter and toasted.",ingredients:["Bread","Garlic","Butter","Parsley","Salt"],instructions:["Mix butter with garlic and parsley.","Spread on sliced bread.","Toast until golden.","Serve warm."],featured:false,calories:260,nutrition:{protein:"6 g",carbs:"30 g",fat:"14 g",fiber:"2 g"},tips:["Use fresh garlic for the best aroma."]},
{id:"mac-and-cheese-2",name:"Mac and Cheese",cuisine:"International",category:"Main Course",difficulty:"Easy",prepTime:"10 mins",cookTime:"20 mins",servings:4,image:"https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=600&q=80",description:"Creamy cheddar pasta, a comfort classic.",ingredients:["Pasta","Cheese","Milk","Butter","Flour","Salt","Black Pepper"],instructions:["Boil pasta.","Make a roux, add milk and cheese.","Combine with pasta.","Serve hot."],featured:false,calories:540,nutrition:{protein:"22 g",carbs:"56 g",fat:"24 g",fiber:"3 g"},tips:["Broil with extra cheese on top for a crust."]},
{id:"mac-and-cheese-bites",name:"Mac and Cheese Bites",cuisine:"International",category:"Appetizer",difficulty:"Medium",prepTime:"15 mins",cookTime:"20 mins",servings:4,image:"https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=600&q=80",description:"Chilled mac and cheese formed into balls, crumbed and fried.",ingredients:["Pasta","Cheese","Milk","Butter","Flour","Breadcrumbs","Egg","Oil"],instructions:["Make mac and cheese, then chill.","Scoop into balls.","Coat in egg and breadcrumbs.","Fry until golden."],featured:false,calories:420,nutrition:{protein:"16 g",carbs:"36 g",fat:"22 g",fiber:"2 g"},tips:["Chill well so they hold their shape."]},
{id:"french-toast-2",name:"French Toast",cuisine:"International",category:"Breakfast",difficulty:"Easy",prepTime:"10 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600&q=80",description:"Custard-soaked bread fried golden and sweet.",ingredients:["Bread","Eggs","Milk","Sugar","Cinnamon","Butter","Vanilla"],instructions:["Whisk eggs, milk, sugar, cinnamon, vanilla.","Dip bread slices.","Fry in butter until golden.","Serve with syrup."],featured:false,calories:420,nutrition:{protein:"16 g",carbs:"48 g",fat:"18 g",fiber:"3 g"},tips:["Dust with powdered sugar before serving."]},
{id:"eggs-benedict",name:"Eggs Benedict",cuisine:"International",category:"Breakfast",difficulty:"Medium",prepTime:"15 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&q=80",description:"Poached eggs and ham on English muffin with hollandaise.",ingredients:["Egg","Bread","Ham","Butter","Lemon","Salt","Black Pepper"],instructions:["Poach the eggs.","Toast the muffin and add ham.","Top with egg and hollandaise.","Season and serve."],featured:false,calories:480,nutrition:{protein:"24 g",carbs:"28 g",fat:"30 g",fiber:"2 g"},tips:["Add a splash of vinegar to the poaching water."]},
{id:"pancakes-2",name:"Pancakes",cuisine:"International",category:"Breakfast",difficulty:"Easy",prepTime:"10 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80",description:"Fluffy golden pancakes for a weekend breakfast.",ingredients:["Flour","Eggs","Milk","Sugar","Baking Powder","Butter","Salt"],instructions:["Whisk dry and wet ingredients.","Rest the batter.","Cook on a buttered pan.","Serve with toppings."],featured:false,calories:460,nutrition:{protein:"14 g",carbs:"66 g",fat:"14 g",fiber:"3 g"},tips:["Wait for bubbles before flipping."]},
{id:"egg-mcmuffin",name:"Egg McMuffin",cuisine:"International",category:"Breakfast",difficulty:"Easy",prepTime:"10 mins",cookTime:"10 mins",servings:2,image:"https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&q=80",description:"Breakfast sandwich of egg, cheese and ham in an English muffin.",ingredients:["Egg","Bread","Cheese","Ham","Butter","Salt"],instructions:["Cook the egg in a ring.","Toast the muffin.","Layer egg, cheese and ham.","Close and serve."],featured:false,calories:380,nutrition:{protein:"22 g",carbs:"28 g",fat:"20 g",fiber:"2 g"},tips:["Use a cookie cutter to shape the egg."]},
{id:"hash-browns",name:"Hash Browns",cuisine:"International",category:"Breakfast",difficulty:"Easy",prepTime:"10 mins",cookTime:"15 mins",servings:3,image:"https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&q=80",description:"Shredded potato patties fried until crisp and golden.",ingredients:["Potato","Onion","Salt","Black Pepper","Oil"],instructions:["Grate and squeeze the potatoes dry.","Mix with onion and seasoning.","Press into patties and fry.","Drain and serve."],featured:false,calories:300,nutrition:{protein:"5 g",carbs:"40 g",fat:"14 g",fiber:"4 g"},tips:["Squeeze out all moisture for crispness."]},
{id:"sausage-biscuit",name:"Sausage Biscuit",cuisine:"International",category:"Breakfast",difficulty:"Easy",prepTime:"10 mins",cookTime:"15 mins",servings:2,image:"https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=600&q=80",description:"Savory sausage patty in a flaky buttermilk biscuit.",ingredients:["Sausage","Flour","Butter","Milk","Baking Powder","Salt"],instructions:["Make biscuit dough and bake.","Cook the sausage patty.","Split the biscuit and add sausage.","Serve warm."],featured:false,calories:460,nutrition:{protein:"18 g",carbs:"38 g",fat:"26 g",fiber:"2 g"},tips:["Keep the butter cold for flaky biscuits."]},
{id:"biscuit-and-gravy",name:"Biscuit and Gravy",cuisine:"International",category:"Breakfast",difficulty:"Medium",prepTime:"15 mins",cookTime:"20 mins",servings:4,image:"https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=600&q=80",description:"Soft biscuits smothered in creamy sausage gravy.",ingredients:["Flour","Butter","Milk","Sausage","Baking Powder","Salt","Black Pepper"],instructions:["Bake the biscuits.","Brown sausage, make a roux, add milk.","Simmer into a thick gravy.","Split biscuits and pour gravy over."],featured:false,calories:520,nutrition:{protein:"18 g",carbs:"40 g",fat:"32 g",fiber:"2 g"},tips:["Season the gravy well with black pepper."]},
{id:"onion-rings",name:"Onion Rings",cuisine:"International",category:"Appetizer",difficulty:"Easy",prepTime:"10 mins",cookTime:"15 mins",servings:4,image:"https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=600&q=80",description:"Thick onion slices in a crisp batter, fried golden.",ingredients:["Onion","Flour","Milk","Egg","Breadcrumbs","Salt","Oil"],instructions:["Separate onion into rings.","Dip in batter then breadcrumbs.","Fry until golden.","Drain and serve."],featured:false,calories:320,nutrition:{protein:"7 g",carbs:"42 g",fat:"14 g",fiber:"3 g"},tips:["Use a wide, sweet onion like Vidalia."]},
{id:"mozzarella-sticks",name:"Mozzarella Sticks",cuisine:"International",category:"Appetizer",difficulty:"Easy",prepTime:"10 mins",cookTime:"10 mins",servings:4,image:"https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&q=80",description:"Breaded mozzarella fried until gooey with a crisp coat.",ingredients:["Cheese","Flour","Egg","Breadcrumbs","Salt","Oil"],instructions:["Cut cheese into sticks.","Coat in flour, egg and breadcrumbs.","Freeze briefly, then fry.","Serve with marinara."],featured:false,calories:360,nutrition:{protein:"18 g",carbs:"24 g",fat:"22 g",fiber:"1 g"},tips:["Freeze before frying so the cheese doesn't leak."]},
{id:"jalapeno-poppers",name:"Jalapeño Poppers",cuisine:"International",category:"Appetizer",difficulty:"Easy",prepTime:"10 mins",cookTime:"15 mins",servings:4,image:"https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=600&q=80",description:"Jalapeños stuffed with cheese, breaded and fried or baked.",ingredients:["Jalapeño","Cheese","Cream Cheese","Breadcrumbs","Egg","Salt"],instructions:["Halve and deseed the peppers.","Fill with cheese mixture.","Coat in egg and breadcrumbs.","Bake or fry until golden."],featured:false,calories:300,nutrition:{protein:"12 g",carbs:"18 g",fat:"20 g",fiber:"3 g"},tips:["Wear gloves when handling the peppers."]},
{id:"curly-fries",name:"Curly Fries",cuisine:"International",category:"Appetizer",difficulty:"Easy",prepTime:"10 mins",cookTime:"20 mins",servings:4,image:"https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&q=80",description:"Spiral-cut fries with a spicy seasoning blend.",ingredients:["Potato","Oil","Paprika","Cumin","Garlic Powder","Salt"],instructions:["Cut potatoes into curls.","Toss with oil and spices.","Bake or fry until crisp.","Serve hot."],featured:false,calories:320,nutrition:{protein:"5 g",carbs:"44 g",fat:"14 g",fiber:"4 g"},tips:["A spiral cutter makes the signature shape."]},
{id:"waffle-fries",name:"Waffle Fries",cuisine:"International",category:"Appetizer",difficulty:"Easy",prepTime:"10 mins",cookTime:"20 mins",servings:4,image:"https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&q=80",description:"Grid-pattern fries baked or fried until crisp.",ingredients:["Potato","Oil","Salt","Black Pepper","Paprika"],instructions:["Slice potatoes into waffle cuts.","Toss with oil and spices.","Bake or fry until golden.","Serve with dip."],featured:false,calories:300,nutrition:{protein:"5 g",carbs:"42 g",fat:"12 g",fiber:"4 g"},tips:["Soak then dry for maximum crispness."]},
{id:"potato-wedges-2",name:"Potato Wedges",cuisine:"International",category:"Appetizer",difficulty:"Easy",prepTime:"10 mins",cookTime:"30 mins",servings:4,image:"https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&q=80",description:"Spiced potato wedges roasted crisp.",ingredients:["Potato","Olive Oil","Paprika","Salt","Black Pepper","Garlic Powder"],instructions:["Cut potatoes into wedges.","Toss with oil and spices.","Bake until crisp.","Serve with dip."],featured:false,calories:280,nutrition:{protein:"5 g",carbs:"42 g",fat:"10 g",fiber:"5 g"},tips:["Cut evenly so they cook at the same rate."]},
{id:"tater-tots",name:"Tater Tots",cuisine:"International",category:"Appetizer",difficulty:"Easy",prepTime:"10 mins",cookTime:"20 mins",servings:4,image:"https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&q=80",description:"Shredded potato shaped into nuggets and fried crisp.",ingredients:["Potato","Flour","Salt","Black Pepper","Oil"],instructions:["Grate and dry the potatoes.","Bind with a little flour.","Shape into tots and fry.","Drain and serve."],featured:false,calories:320,nutrition:{protein:"5 g",carbs:"40 g",fat:"16 g",fiber:"4 g"},tips:["Bake for a lighter version."]},
{id:"sweet-potato-fries",name:"Sweet Potato Fries",cuisine:"International",category:"Appetizer",difficulty:"Easy",prepTime:"10 mins",cookTime:"20 mins",servings:4,image:"https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&q=80",description:"Sweet potato fries with a lightly spiced coat.",ingredients:["Sweet Potato","Olive Oil","Paprika","Salt","Cinnamon"],instructions:["Cut sweet potato into fries.","Toss with oil and spices.","Bake until crisp at the edges.","Serve warm."],featured:false,calories:260,nutrition:{protein:"3 g",carbs:"46 g",fat:"8 g",fiber:"6 g"},tips:["Don't crowd the tray or they'll steam."]},
{id:"cinnamon-twists",name:"Cinnamon Twists",cuisine:"International",category:"Dessert",difficulty:"Medium",prepTime:"15 mins",cookTime:"15 mins",servings:4,image:"https://images.unsplash.com/photo-1558326567-98ae2405596b?w=600&q=80",description:"Fried dough twists dusted with cinnamon sugar.",ingredients:["Flour","Sugar","Cinnamon","Butter","Egg","Oil"],instructions:["Make a soft dough.","Roll, cut and twist into strips.","Fry until golden.","Toss in cinnamon sugar."],featured:false,calories:340,nutrition:{protein:"6 g",carbs:"52 g",fat:"12 g",fiber:"2 g"},tips:["Toss while warm so sugar sticks."]},
{id:"donuts",name:"Donuts",cuisine:"International",category:"Dessert",difficulty:"Medium",prepTime:"20 mins",cookTime:"15 mins",servings:6,image:"https://images.unsplash.com/photo-1551024601-bec78aea704b?w=600&q=80",description:"Soft fried donuts glazed or dusted with sugar.",ingredients:["Flour","Sugar","Milk","Yeast","Egg","Butter","Oil"],instructions:["Make and proof a yeast dough.","Cut into rings and proof again.","Fry until golden.","Glaze or sugar-coat."],featured:false,calories:380,nutrition:{protein:"6 g",carbs:"52 g",fat:"16 g",fiber:"2 g"},tips:["Let them cool slightly before glazing."]},
{id:"milkshake",name:"Milkshake",cuisine:"International",category:"Dessert",difficulty:"Easy",prepTime:"5 mins",cookTime:"0 mins",servings:2,image:"https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&q=80",description:"Thick blended milkshake with ice cream.",ingredients:["Milk","Ice Cream","Sugar","Vanilla"],instructions:["Add milk, ice cream and sugar to a blender.","Blend until smooth.","Pour and serve."],featured:false,calories:360,nutrition:{protein:"9 g",carbs:"50 g",fat:"14 g",fiber:"1 g"},tips:["Use frozen fruit for flavour twists."]},
{id:"ice-cream-cone",name:"Ice Cream Cone",cuisine:"International",category:"Dessert",difficulty:"Easy",prepTime:"5 mins",cookTime:"0 mins",servings:2,image:"https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80",description:"Scoops of ice cream in a crisp waffle cone.",ingredients:["Milk","Sugar","Cream","Ice Cream Cone"],instructions:["Scoop ice cream into the cone.","Top with a second scoop.","Serve immediately."],featured:false,calories:300,nutrition:{protein:"6 g",carbs:"42 g",fat:"12 g",fiber:"1 g"},tips:["Add sprinkles or a cherry on top."]},
{id:"apple-fritter",name:"Apple Fritter",cuisine:"International",category:"Dessert",difficulty:"Medium",prepTime:"15 mins",cookTime:"15 mins",servings:4,image:"https://images.unsplash.com/photo-1568051243858-533a607809a5?w=600&q=80",description:"Apple pieces in a cinnamon batter, fried and sugared.",ingredients:["Apple","Flour","Sugar","Cinnamon","Egg","Milk","Oil"],instructions:["Mix batter with cinnamon.","Fold in diced apple.","Drop spoonfuls into hot oil.","Drain and sugar-coat."],featured:false,calories:360,nutrition:{protein:"5 g",carbs:"54 g",fat:"14 g",fiber:"3 g"},tips:["Use firm apples so they hold shape."]},
{id:"cinnamon-rolls",name:"Cinnamon Rolls",cuisine:"International",category:"Dessert",difficulty:"Medium",prepTime:"20 mins",cookTime:"20 mins",servings:6,image:"https://images.unsplash.com/photo-1558326567-98ae2405596b?w=600&q=80",description:"Soft rolled dough with cinnamon sugar, topped with icing.",ingredients:["Flour","Sugar","Cinnamon","Butter","Milk","Yeast","Cream Cheese"],instructions:["Make and roll out a yeast dough.","Spread butter and cinnamon sugar.","Roll up and slice, then bake.","Ice with cream cheese glaze."],featured:false,calories:420,nutrition:{protein:"7 g",carbs:"62 g",fat:"16 g",fiber:"2 g"},tips:["Don't overbake or they dry out."]},
{id:"achar-paratha",name:"Achar Paratha",cuisine:"Pakistani",category:"Breakfast",difficulty:"Medium",prepTime:"20 mins",cookTime:"20 mins",servings:3,image:"https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80",description:"Flatbread stuffed with tangy pickle and spices.",ingredients:["Whole Wheat Flour","Pickle","Onion","Coriander","Cumin","Ghee","Salt"],instructions:["Mix pickle and spices into a stuffing.","Stuff into dough balls.","Roll out gently.","Cook on a griddle with ghee."],featured:false,calories:340,nutrition:{protein:"8 g",carbs:"50 g",fat:"12 g",fiber:"6 g"},tips:["Use a dry pickle so the paratha isn't soggy."]},
{id:"kabab-roll",name:"Kabab Roll",cuisine:"Pakistani",category:"Main Course",difficulty:"Medium",prepTime:"20 mins",cookTime:"20 mins",servings:3,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Spiced seekh kebab wrapped in a paratha with chutney and onions.",ingredients:["Minced Meat","Bread","Onion","Coriander","Green Chili","Garam Masala","Yogurt"],instructions:["Season and shape the mince into kebabs.","Grill or fry until cooked.","Warm the paratha.","Roll with kebab, onion and chutney."],featured:false,calories:520,nutrition:{protein:"32 g",carbs:"40 g",fat:"24 g",fiber:"4 g"},tips:["Add a squeeze of lemon for brightness."]},
{id:"chicken-roll",name:"Chicken Roll",cuisine:"Pakistani",category:"Main Course",difficulty:"Medium",prepTime:"20 mins",cookTime:"20 mins",servings:3,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",description:"Spicy chicken filling rolled in a paratha with salad.",ingredients:["Chicken","Bread","Onion","Tomato","Coriander","Cumin","Yogurt"],instructions:["Cook spiced chicken.","Warm the paratha.","Add chicken, onion and chutney.","Roll up and serve."],featured:false,calories:480,nutrition:{protein:"30 g",carbs:"40 g",fat:"20 g",fiber:"4 g"},tips:["Use boneless thigh for juicier rolls."]},
{id:"daal",name:"Daal",cuisine:"Pakistani",category:"Curry",difficulty:"Easy",prepTime:"10 mins",cookTime:"30 mins",servings:4,image:"https://images.unsplash.com/photo-1631292784640-2b24be784d5d?w=600&q=80",description:"Simple tempered lentils, a comforting everyday curry.",ingredients:["Lentils","Onion","Garlic","Tomato","Turmeric","Cumin","Red Chili Powder","Ghee","Salt"],instructions:["Boil lentils with turmeric and salt.","Fry onion, garlic and tomato with spices.","Add to the lentils and simmer.","Serve with rice or roti."],featured:false,calories:400,nutrition:{protein:"16 g",carbs:"60 g",fat:"9 g",fiber:"10 g"},tips:["A garlic tadka at the end adds depth."]},
{id:"daal-fry",name:"Daal Fry",cuisine:"Pakistani",category:"Curry",difficulty:"Easy",prepTime:"10 mins",cookTime:"30 mins",servings:4,image:"https://images.unsplash.com/photo-1631292784640-2b24be784d5d?w=600&q=80",description:"Lentils finished with a fried onion and spice tempering.",ingredients:["Lentils","Onion","Garlic","Tomato","Turmeric","Cumin","Garam Masala","Ghee","Salt"],instructions:["Boil the lentils until soft.","Fry onion, garlic and spices in ghee.","Pour over the lentils.","Simmer and serve."],featured:false,calories:410,nutrition:{protein:"16 g",carbs:"60 g",fat:"10 g",fiber:"10 g"},tips:["Keep the tadka dark for a stronger flavour."]},
{id:"aloo-paratha-2",name:"Aloo Paratha",cuisine:"Pakistani",category:"Breakfast",difficulty:"Medium",prepTime:"20 mins",cookTime:"20 mins",servings:3,image:"https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80",description:"Potato-stuffed flatbread cooked on a griddle.",ingredients:["Potato","Whole Wheat Flour","Onion","Coriander","Cumin","Green Chili","Ghee","Salt"],instructions:["Mash spiced potatoes.","Stuff into dough.","Roll out gently.","Cook with ghee until spotted."],featured:false,calories:360,nutrition:{protein:"8 g",carbs:"58 g",fat:"10 g",fiber:"6 g"},tips:["Roll gently to avoid tearing."]},
{id:"plain-paratha",name:"Plain Paratha",cuisine:"Pakistani",category:"Breakfast",difficulty:"Easy",prepTime:"15 mins",cookTime:"15 mins",servings:3,image:"https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80",description:"Layered whole-wheat flatbread with a flaky, buttery finish.",ingredients:["Whole Wheat Flour","Ghee","Salt","Water"],instructions:["Knead a soft dough.","Roll, fold with ghee, and roll again.","Cook on a griddle until flaky.","Serve warm."],featured:false,calories:280,nutrition:{protein:"7 g",carbs:"44 g",fat:"9 g",fiber:"6 g"},tips:["Brush ghee between folds for layers."]}
];

/* Map legacy fields to the unified RECIPES schema, preserving any data that
   is already provided (description, ingredients, instructions, calories,
   nutrition, tips) instead of overwriting it with placeholders. */
const legacyMap = {
  prep: r => r.prepTime,
  cook: r => r.cookTime,
  calories: r => (typeof r.calories === 'number' ? r.calories : 500),
  steps: r => (Array.isArray(r.instructions) && r.instructions.length ? r.instructions : []),
  tips: r => (Array.isArray(r.tips) ? r.tips : []),
  nutrition: r => (r.nutrition && typeof r.nutrition === 'object' ? r.nutrition : { protein: "-", carbs: "-", fat: "-", fiber: "-" })
};

recipes.forEach(r => {
  const mapped = { ...r };
  Object.keys(legacyMap).forEach(k => { mapped[k] = legacyMap[k](r); });
  if (!mapped.id) mapped.id = "r" + (RECIPES.length + 1);
  mapped.ingredients = mapped.ingredients || [];
  mapped.steps = mapped.steps || [];
  mapped.tips = mapped.tips || [];
  mapped.nutrition = mapped.nutrition || { protein: "-", carbs: "-", fat: "-", fiber: "-" };
  RECIPES.push(mapped);
});
