/* Italian & American recipes */
addRecipe({ name: "Spaghetti Carbonara", cuisine: "Italian", category: "Main Course", difficulty: "Medium", prep: "10 min", cook: "15 min", servings: 4, calories: 580, image: "https://picsum.photos/seed/spaghetti-carbonara/600/400", description: "Roman pasta with egg, cured pork, pecorino and black pepper.", ingredients: ["Spaghetti","Egg","Pancetta","Pecorino Cheese","Black Pepper","Salt"], steps: ["Boil spaghetti.","Crisp pancetta.","Whisk eggs with cheese.","Toss hot pasta with egg mix off heat.","Top with pancetta and pepper."], tips: ["Use residual heat to cook the egg.","Do not let it scramble."], nutrition: { protein: "26 g", carbs: "62 g", fat: "24 g", fiber: "3 g" } });

addRecipe({ name: "Pizza Napoletana", cuisine: "Italian", category: "Main Course", difficulty: "Medium", prep: "20 min", cook: "12 min", servings: 2, calories: 600, image: "https://picsum.photos/seed/pizza-napoletana/600/400", description: "Classic Neapolitan pizza with tomato, mozzarella and basil.", ingredients: ["Pizza Dough","San Marzano Tomatoes","Fresh Mozzarella","Basil","Olive Oil","Salt","Yeast","Flour"], steps: ["Stretch dough thin.","Top with crushed tomato and mozzarella.","Bake in hot oven.","Finish with basil and oil."], tips: ["Use a very hot oven.","Do not overload toppings."], nutrition: { protein: "24 g", carbs: "72 g", fat: "22 g", fiber: "4 g" } });

addRecipe({ name: "Lasagna", cuisine: "Italian", category: "Main Course", difficulty: "Hard", prep: "30 min", cook: "45 min", servings: 6, calories: 650, image: "https://picsum.photos/seed/lasagna/600/400", description: "Layered pasta with ragù, béchamel and cheese.", ingredients: ["Lasagna Sheets","Ground Beef","Tomato Sauce","Béchamel","Parmesan","Mozzarella","Onion","Garlic","Olive Oil","Salt"], steps: ["Make ragù.","Make béchamel.","Layer pasta, ragù and béchamel.","Top with cheese.","Bake until bubbly."], tips: ["Rest before slicing.","Use fresh pasta for less time."], nutrition: { protein: "34 g", carbs: "48 g", fat: "30 g", fiber: "5 g" } });

addRecipe({ name: "Risotto ai Funghi", cuisine: "Italian", category: "Main Course", difficulty: "Medium", prep: "15 min", cook: "30 min", servings: 4, calories: 420, image: "https://picsum.photos/seed/risotto-ai-funghi/600/400", description: "Creamy arborio rice with porcini mushrooms.", ingredients: ["Arborio Rice","Porcini Mushrooms","Onion","White Wine","Parmesan","Butter","Vegetable Stock","Garlic","Olive Oil","Salt"], steps: ["Sauté onion and mushrooms.","Toast rice.","Add wine and stock gradually.","Stir until creamy.","Finish with butter and cheese."], tips: ["Stir often for creaminess.","Keep stock warm."], nutrition: { protein: "11 g", carbs: "58 g", fat: "13 g", fiber: "3 g" } });

addRecipe({ name: "Osso Buco", cuisine: "Italian", category: "Main Course", difficulty: "Hard", prep: "20 min", cook: "120 min", servings: 4, calories: 540, image: "https://picsum.photos/seed/osso-buco/600/400", description: "Braised veal shanks with gremolata.", ingredients: ["Veal Shanks","Carrot","Celery","Onion","Tomato","White Wine","Stock","Garlic","Parsley","Lemon","Flour","Olive Oil"], steps: ["Sear shanks.","Sauté vegetables.","Add wine and stock.","Braise low and slow.","Top with gremolata."], tips: ["Cook until fork tender.","Skim fat before serving."], nutrition: { protein: "40 g", carbs: "14 g", fat: "28 g", fiber: "3 g" } });

addRecipe({ name: "Caprese Salad", cuisine: "Italian", category: "Salad", difficulty: "Easy", prep: "10 min", cook: "0 min", servings: 2, calories: 320, image: "https://picsum.photos/seed/caprese-salad/600/400", description: "Tomato, mozzarella and basil with olive oil.", ingredients: ["Tomato","Fresh Mozzarella","Basil","Olive Oil","Salt","Black Pepper"], steps: ["Slice tomato and mozzarella.","Layer with basil.","Drizzle oil and season."], tips: ["Use ripe tomatoes.","Serve at room temp."], nutrition: { protein: "18 g", carbs: "8 g", fat: "24 g", fiber: "2 g" } });

addRecipe({ name: "Bruschetta", cuisine: "Italian", category: "Appetizer", difficulty: "Easy", prep: "10 min", cook: "5 min", servings: 4, calories: 180, image: "https://picsum.photos/seed/bruschetta/600/400", description: "Toasted bread with tomato and basil.", ingredients: ["Baguette","Tomato","Garlic","Basil","Olive Oil","Salt"], steps: ["Toast bread.","Rub with garlic.","Top with tomato mix.","Drizzle oil."], tips: ["Toast just before serving.","Use good olive oil."], nutrition: { protein: "5 g", carbs: "26 g", fat: "7 g", fiber: "2 g" } });

addRecipe({ name: "Tiramisu", cuisine: "Italian", category: "Dessert", difficulty: "Medium", prep: "30 min", cook: "0 min", servings: 8, calories: 380, image: "https://picsum.photos/seed/tiramisu/600/400", description: "Coffee-soaked ladyfingers with mascarpone cream.", ingredients: ["Ladyfingers","Mascarpone","Egg","Sugar","Espresso","Cocoa Powder","Marsala Wine","Salt"], steps: ["Make mascarpone cream.","Dip ladyfingers in espresso.","Layer cream and cookies.","Chill.","Dust with cocoa."], tips: ["Chill overnight.","Do not oversoak cookies."], nutrition: { protein: "8 g", carbs: "34 g", fat: "22 g", fiber: "1 g" } });

addRecipe({ name: "Panna Cotta", cuisine: "Italian", category: "Dessert", difficulty: "Easy", prep: "15 min", cook: "10 min", servings: 6, calories: 290, image: "https://picsum.photos/seed/panna-cotta/600/400", description: "Silky cooked cream set with gelatin.", ingredients: ["Cream","Milk","Sugar","Gelatin","Vanilla","Berries"], steps: ["Warm cream and sugar.","Dissolve gelatin.","Pour into molds.","Chill until set.","Top with berries."], tips: ["Do not boil cream.","Unmold with warm knife."], nutrition: { protein: "4 g", carbs: "22 g", fat: "21 g", fiber: "1 g" } });

addRecipe({ name: "Gnocchi", cuisine: "Italian", category: "Main Course", difficulty: "Medium", prep: "30 min", cook: "10 min", servings: 4, calories: 410, image: "https://picsum.photos/seed/gnocchi/600/400", description: "Soft potato dumplings with sage butter.", ingredients: ["Potato","Flour","Egg","Parmesan","Butter","Sage","Salt","Nutmeg"], steps: ["Cook and mash potatoes.","Mix with flour and egg.","Shape dumplings.","Boil until they float.","Toss in sage butter."], tips: ["Use dry potatoes.","Do not overwork dough."], nutrition: { protein: "10 g", carbs: "64 g", fat: "12 g", fiber: "4 g" } });

addRecipe({ name: "Penne Arrabbiata", cuisine: "Italian", category: "Main Course", difficulty: "Easy", prep: "10 min", cook: "20 min", servings: 4, calories: 470, image: "https://picsum.photos/seed/penne-arrabbiata/600/400", description: "Penne in spicy tomato sauce.", ingredients: ["Penne","Tomato","Garlic","Red Chili","Olive Oil","Parsley","Salt"], steps: ["Cook penne.","Sauté garlic and chili.","Add tomato and simmer.","Toss pasta with sauce."], tips: ["Adjust chili to taste.","Finish with parsley."], nutrition: { protein: "14 g", carbs: "76 g", fat: "12 g", fiber: "5 g" } });

addRecipe({ name: "Minestrone", cuisine: "Italian", category: "Soup", difficulty: "Easy", prep: "15 min", cook: "40 min", servings: 6, calories: 220, image: "https://picsum.photos/seed/minestrone/600/400", description: "Hearty vegetable and bean soup with pasta.", ingredients: ["Beans","Carrot","Celery","Onion","Tomato","Zucchini","Pasta","Stock","Garlic","Olive Oil","Salt","Basil"], steps: ["Sauté vegetables.","Add stock and beans.","Simmer.","Add pasta near end.","Serve with basil."], tips: ["Use seasonal vegetables.","Add pesto to finish."], nutrition: { protein: "10 g", carbs: "36 g", fat: "5 g", fiber: "9 g" } });

addRecipe({ name: "BBQ Ribs", cuisine: "American", category: "BBQ", difficulty: "Hard", prep: "20 min", cook: "180 min", servings: 4, calories: 720, image: "https://picsum.photos/seed/bbq-ribs/600/400", description: "Slow-smoked pork ribs with sticky sauce.", ingredients: ["Pork Ribs","Brown Sugar","Paprika","Garlic Powder","Salt","Pepper","BBQ Sauce","Apple Cider Vinegar","Onion Powder","Cayenne"], steps: ["Make dry rub.","Coat ribs and rest.","Smoke low and slow.","Glaze with sauce.","Rest and slice."], tips: ["Cook to 203 F internal.","Wrap for tenderness."], nutrition: { protein: "45 g", carbs: "22 g", fat: "50 g", fiber: "1 g" } });

addRecipe({ name: "Buffalo Wings", cuisine: "American", category: "Appetizer", difficulty: "Easy", prep: "15 min", cook: "30 min", servings: 4, calories: 430, image: "https://picsum.photos/seed/buffalo-wings/600/400", description: "Crispy chicken wings in spicy buffalo sauce.", ingredients: ["Chicken Wings","Hot Sauce","Butter","Flour","Salt","Pepper","Garlic Powder","Celery","Blue Cheese Dressing"], steps: ["Coat wings in flour.","Bake or fry until crisp.","Toss in buffalo sauce.","Serve with celery."], tips: ["Dry wings before coating.","Toss sauce while hot."], nutrition: { protein: "28 g", carbs: "18 g", fat: "28 g", fiber: "1 g" } });

addRecipe({ name: "Clam Chowder", cuisine: "American", category: "Soup", difficulty: "Medium", prep: "20 min", cook: "35 min", servings: 4, calories: 380, image: "https://picsum.photos/seed/clam-chowder/600/400", description: "Creamy New England clam chowder.", ingredients: ["Clams","Potato","Onion","Bacon","Cream","Milk","Flour","Butter","Celery","Salt","Pepper"], steps: ["Cook bacon and vegetables.","Add clams and broth.","Add potatoes and simmer.","Stir in cream.","Serve hot."], tips: ["Use fresh clams if possible.","Do not boil after cream."], nutrition: { protein: "18 g", carbs: "28 g", fat: "22 g", fiber: "3 g" } });

addRecipe({ name: "Cheesecake", cuisine: "American", category: "Dessert", difficulty: "Medium", prep: "25 min", cook: "55 min", servings: 8, calories: 450, image: "https://picsum.photos/seed/cheesecake/600/400", description: "Creamy baked cheesecake with graham crust.", ingredients: ["Cream Cheese","Sugar","Egg","Graham Crackers","Butter","Sour Cream","Vanilla","Lemon","Salt"], steps: ["Make crust.","Beat cheese and sugar.","Add eggs and vanilla.","Bake in water bath.","Chill before serving."], tips: ["Avoid overmixing.","Cool slowly to prevent cracks."], nutrition: { protein: "8 g", carbs: "38 g", fat: "30 g", fiber: "1 g" } });

addRecipe({ name: "Meatloaf", cuisine: "American", category: "Main Course", difficulty: "Easy", prep: "20 min", cook: "60 min", servings: 6, calories: 480, image: "https://picsum.photos/seed/meatloaf/600/400", description: "Classic beef meatloaf with ketchup glaze.", ingredients: ["Ground Beef","Breadcrumbs","Egg","Onion","Ketchup","Worcestershire","Garlic","Salt","Pepper","Milk"], steps: ["Mix meat and binders.","Shape into loaf.","Glaze with ketchup.","Bake.","Rest and slice."], tips: ["Do not pack too tight.","Use a thermometer."], nutrition: { protein: "32 g", carbs: "24 g", fat: "28 g", fiber: "2 g" } });

addRecipe({ name: "Cornbread", cuisine: "American", category: "Breakfast", difficulty: "Easy", prep: "10 min", cook: "25 min", servings: 8, calories: 210, image: "https://picsum.photos/seed/cornbread/600/400", description: "Sweet golden cornmeal bread.", ingredients: ["Cornmeal","Flour","Buttermilk","Egg","Sugar","Baking Powder","Salt","Butter"], steps: ["Mix dry and wet.","Pour into pan.","Bake until golden.","Cool slightly."], tips: ["Do not overmix.","Serve warm with butter."], nutrition: { protein: "5 g", carbs: "30 g", fat: "8 g", fiber: "2 g" } });

addRecipe({ name: "Apple Pie", cuisine: "American", category: "Dessert", difficulty: "Medium", prep: "30 min", cook: "50 min", servings: 8, calories: 410, image: "https://picsum.photos/seed/apple-pie/600/400", description: "Spiced apple filling in flaky crust.", ingredients: ["Apples","Sugar","Cinnamon","Flour","Butter","Pie Crust","Lemon","Nutmeg","Salt","Egg"], steps: ["Make pie crust.","Fill with spiced apples.","Top with crust.","Bake until bubbly.","Cool before slicing."], tips: ["Use firm apples.","Vent the top crust."], nutrition: { protein: "4 g", carbs: "58 g", fat: "18 g", fiber: "4 g" } });

addRecipe({ name: "Chicken Fried Steak", cuisine: "American", category: "Main Course", difficulty: "Medium", prep: "15 min", cook: "20 min", servings: 4, calories: 560, image: "https://picsum.photos/seed/chicken-fried-steak/600/400", description: "Breaded beef cutlet with cream gravy.", ingredients: ["Beef Cube Steak","Flour","Egg","Milk","Salt","Pepper","Oil","Butter","Onion","Cream"], steps: ["Bread the steak.","Fry until golden.","Make gravy from drippings.","Serve smothered in gravy."], tips: ["Pound steak thin.","Season the flour well."], nutrition: { protein: "34 g", carbs: "30 g", fat: "34 g", fiber: "1 g" } });

addRecipe({ name: "Chili", cuisine: "American", category: "Main Course", difficulty: "Easy", prep: "15 min", cook: "60 min", servings: 6, calories: 390, image: "https://picsum.photos/seed/chili/600/400", description: "Hearty beef and bean chili.", ingredients: ["Ground Beef","Beans","Tomato","Onion","Garlic","Chili Powder","Cumin","Paprika","Stock","Salt","Pepper","Jalapeno"], steps: ["Brown beef.","Sauté onion and garlic.","Add spices and tomato.","Simmer with beans.","Serve hot."], tips: ["Let it simmer long.","Top with cheese."], nutrition: { protein: "28 g", carbs: "32 g", fat: "16 g", fiber: "9 g" } });

addRecipe({ name: "Brownies", cuisine: "American", category: "Dessert", difficulty: "Easy", prep: "15 min", cook: "30 min", servings: 12, calories: 320, image: "https://picsum.photos/seed/brownies/600/400", description: "Fudgy chocolate brownies.", ingredients: ["Chocolate","Butter","Sugar","Egg","Flour","Cocoa","Vanilla","Salt","Walnuts"], steps: ["Melt chocolate and butter.","Beat eggs and sugar.","Fold in dry ingredients.","Bake.","Cool and cut."], tips: ["Do not overbake.","Use good chocolate."], nutrition: { protein: "4 g", carbs: "38 g", fat: "18 g", fiber: "2 g" } });

addRecipe({ name: "Caesar Salad", cuisine: "American", category: "Salad", difficulty: "Easy", prep: "15 min", cook: "5 min", servings: 4, calories: 290, image: "https://picsum.photos/seed/caesar-salad/600/400", description: "Romaine with creamy Caesar dressing and croutons.", ingredients: ["Romaine","Parmesan","Croutons","Garlic","Anchovy","Egg Yolk","Lemon","Olive Oil","Worcestershire","Salt","Pepper"], steps: ["Make dressing.","Chop romaine.","Toss with dressing.","Top with croutons and cheese."], tips: ["Use fresh croutons.","Emulsify the dressing."], nutrition: { protein: "9 g", carbs: "14 g", fat: "22 g", fiber: "3 g" } });

addRecipe({ name: "Philly Cheesesteak", cuisine: "American", category: "Main Course", difficulty: "Medium", prep: "15 min", cook: "20 min", servings: 2, calories: 620, image: "https://picsum.photos/seed/philly-cheesesteak/600/400", description: "Thin beef and melted cheese in a hoagie.", ingredients: ["Ribeye","Onion","Bell Pepper","Provolone","Hoagie Roll","Salt","Pepper","Oil"], steps: ["Sauté onions and peppers.","Cook thin beef.","Melt cheese on top.","Pile into roll."], tips: ["Slice beef very thin.","Use fresh roll."], nutrition: { protein: "38 g", carbs: "44 g", fat: "32 g", fiber: "3 g" } });

addRecipe({ name: "Pulled Pork", cuisine: "American", category: "BBQ", difficulty: "Hard", prep: "20 min", cook: "480 min", servings: 8, calories: 480, image: "https://picsum.photos/seed/pulled-pork/600/400", description: "Slow-cooked pork shoulder with BBQ sauce.", ingredients: ["Pork Shoulder","Brown Sugar","Paprika","Salt","Pepper","Garlic Powder","Onion Powder","BBQ Sauce","Apple Cider Vinegar","Cayenne"], steps: ["Rub the pork.","Smoke or slow-cook.","Shred the meat.","Toss with sauce.","Serve on buns."], tips: ["Cook until it pulls apart.","Rest before shredding."], nutrition: { protein: "42 g", carbs: "18 g", fat: "28 g", fiber: "1 g" } });
